/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.biblioteca.view;

import static br.com.biblioteca.main.Main.alunos;
import br.com.biblioteca.model.Aluno;
import java.awt.Color;
import java.awt.Frame;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rf
 */
public class TelaPesquisaAluno extends javax.swing.JDialog {

    /**
     * Creates new form TelaPesquisaAluno
     */
    private Frame parent;
    public TelaPesquisaAluno(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        buscarAluno(false);
        this.parent = parent;
        this.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        txtBuscaAluno.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        txtBuscaAluno = new javax.swing.JTextField();
        btnInformacoes = new javax.swing.JButton();
        comboBoxBusca = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaListaAluno = new javax.swing.JTable();
        btnPesquisar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnAlugarLivro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        kGradientPanel1.setkEndColor(new java.awt.Color(107, 22, 22));
        kGradientPanel1.setkGradientFocus(250);
        kGradientPanel1.setkStartColor(new java.awt.Color(75, 77, 75));

        jPanel1.setBackground(new java.awt.Color(1, 19, 123));

        jLabel3.setFont(new java.awt.Font("UnPilgi", 1, 48)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Pesquisar Aluno");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/biblioteca/images/buscaraluno.png"))); // NOI18N

        btnVoltar.setBackground(new java.awt.Color(255, 255, 255));
        btnVoltar.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/biblioteca/images/back.png"))); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVoltarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVoltarMouseEntered(evt);
            }
        });
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(167, 167, 167)
                .addComponent(jLabel3)
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addContainerGap(339, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );

        txtBuscaAluno.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        txtBuscaAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscaAlunoActionPerformed(evt);
            }
        });
        txtBuscaAluno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscaAlunoKeyPressed(evt);
            }
        });

        btnInformacoes.setBackground(new java.awt.Color(255, 255, 255));
        btnInformacoes.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnInformacoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/biblioteca/images/info.png"))); // NOI18N
        btnInformacoes.setText("Informações");
        btnInformacoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInformacoesMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInformacoesMouseEntered(evt);
            }
        });
        btnInformacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformacoesActionPerformed(evt);
            }
        });

        comboBoxBusca.setBackground(new java.awt.Color(255, 255, 255));
        comboBoxBusca.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        comboBoxBusca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "Matricula", "Com Livros" }));

        tabelaListaAluno.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        tabelaListaAluno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Matricula", "Curso", "CPF", "Numero de Livros"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaListaAluno.setRowHeight(30);
        jScrollPane1.setViewportView(tabelaListaAluno);

        btnPesquisar.setBackground(new java.awt.Color(255, 255, 255));
        btnPesquisar.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/biblioteca/images/loupe.png"))); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPesquisarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPesquisarMouseEntered(evt);
            }
        });
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnEditar.setBackground(new java.awt.Color(255, 255, 255));
        btnEditar.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/biblioteca/images/pencil.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditarMouseEntered(evt);
            }
        });
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setBackground(new java.awt.Color(255, 255, 255));
        btnExcluir.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/biblioteca/images/delete.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExcluirMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExcluirMouseEntered(evt);
            }
        });
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAlugarLivro.setBackground(new java.awt.Color(255, 255, 255));
        btnAlugarLivro.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnAlugarLivro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/biblioteca/images/emprestimoLivro2.png"))); // NOI18N
        btnAlugarLivro.setText("Alugar Livro");
        btnAlugarLivro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAlugarLivroMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAlugarLivroMouseEntered(evt);
            }
        });
        btnAlugarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlugarLivroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1018, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(txtBuscaAluno)
                        .addGap(18, 18, 18)
                        .addComponent(comboBoxBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(btnInformacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(btnAlugarLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInformacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlugarLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscaAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscaAlunoActionPerformed

    private void btnInformacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformacoesActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = tabelaListaAluno.getSelectedRow();
        if(linhaSelecionada == -1){
                JOptionPane.showMessageDialog(this, "Nenhum Aluno Selecionado", "Falha ao Ver as Informações", JOptionPane.WARNING_MESSAGE);
                return;
        }
        Aluno aluno = new Aluno();
        try{
            Object obj = tabelaListaAluno.getValueAt(linhaSelecionada, 1);
            String matricula = String.valueOf(obj);
            int matricula_aluno = Integer.parseInt(matricula);
            aluno = alunos.getAlunoMatricula(matricula_aluno);
            TelaInfoEditAluno telaInfoEditAluno = new TelaInfoEditAluno(this.parent, false, aluno, false, false);
            telaInfoEditAluno.setVisible(true);
            telaInfoEditAluno.setLocationRelativeTo(null);
            dispose();
        }catch(NullPointerException ex){
            JOptionPane.showMessageDialog(this, "Erro ao Selecionar o Aluno", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        
        
        
    }//GEN-LAST:event_btnInformacoesActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:
        buscarAluno(true);
        
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = tabelaListaAluno.getSelectedRow();
        if(linhaSelecionada == -1){
                JOptionPane.showMessageDialog(this, "Nenhum Aluno Selecionado", "Falha ao Editar as Informações", JOptionPane.WARNING_MESSAGE);
                return;
        }
        Aluno aluno = new Aluno();
        try{
            Object obj = tabelaListaAluno.getValueAt(linhaSelecionada, 1);
            String matricula = String.valueOf(obj);
            int matricula_aluno = Integer.parseInt(matricula);
            aluno = alunos.getAlunoMatricula(matricula_aluno);
            TelaInfoEditAluno telaInfoEditAluno = new TelaInfoEditAluno(this.parent, false, aluno, true, false);
            telaInfoEditAluno.setVisible(true);
            telaInfoEditAluno.setLocationRelativeTo(null);
            dispose();
        }catch(NullPointerException ex){
            JOptionPane.showMessageDialog(this, "Erro ao Selecionar o Aluno", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = tabelaListaAluno.getSelectedRow();
            if(linhaSelecionada == -1){
                JOptionPane.showMessageDialog(this, "Nenhum Aluno Selecionado", "Falha na Exclusão", JOptionPane.WARNING_MESSAGE);
                return;
            }
            removerAluno(linhaSelecionada);
            
            limparTabela();
            txtBuscaAluno.setText("");
            buscarAluno(false);
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void removerAluno(int index){
        int decisaodeExcluir = 0;
        Aluno aluno = new Aluno();
           try{
                Object obj = tabelaListaAluno.getValueAt(index, 1);
                String matricula = String.valueOf(obj);
                int matricula_aluno = Integer.parseInt(matricula);
                aluno = alunos.getAlunoMatricula(matricula_aluno);
                decisaodeExcluir = JOptionPane.showOptionDialog(this, "Deseja Realmente Excluir o Aluno " + aluno.getNome() , "Decisão de Exclusão", JOptionPane.YES_OPTION, JOptionPane.NO_OPTION, null, null, null);
                if(decisaodeExcluir == 0){
                    if(aluno.getQuantidadeLivrosAlugados() > 0){
                        JOptionPane.showMessageDialog(this, "O aluno possui livros alugados", "Erro ao Realizar a Exclusão", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                    alunos.removerAluno(aluno);
                    JOptionPane.showMessageDialog(this, "Aluno Excluido", "Exclusão Efetuada", JOptionPane.INFORMATION_MESSAGE);
                }
           }catch(NullPointerException ex){
               JOptionPane.showMessageDialog(this, "Erro ao Realizar a Exclusão", "Erro", JOptionPane.ERROR_MESSAGE);
           }

           
    }
    
     
    
    private void btnAlugarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlugarLivroActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = tabelaListaAluno.getSelectedRow();
        if(linhaSelecionada == -1){
                JOptionPane.showMessageDialog(this, "Nenhum Aluno Selecionado", "Falha ao Alugar o Livro", JOptionPane.WARNING_MESSAGE);
                return;
        }
        Aluno aluno = new Aluno();
        try{
            Object obj = tabelaListaAluno.getValueAt(linhaSelecionada, 1);
            String matricula = String.valueOf(obj);
            int matricula_aluno = Integer.parseInt(matricula);
            aluno = alunos.getAlunoMatricula(matricula_aluno);
            TelaSolicitarEmprestimo solicitarEmprestimo = new TelaSolicitarEmprestimo(this.parent, false, aluno);
            solicitarEmprestimo.setVisible(true);
            solicitarEmprestimo.setLocationRelativeTo(null);
            dispose();
        }catch(NullPointerException ex){
            JOptionPane.showMessageDialog(this, "Erro ao Selecionar o Aluno", "Erro", JOptionPane.ERROR_MESSAGE);
        }
                                 
    }//GEN-LAST:event_btnAlugarLivroActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        txtBuscaAluno.setText("");
        dispose();
        this.parent.enable();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void txtBuscaAlunoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaAlunoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == evt.VK_ENTER)
            buscarAluno(true);
    }//GEN-LAST:event_txtBuscaAlunoKeyPressed

    private void btnVoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarMouseEntered
        // TODO add your handling code here:
        btnVoltar.setBackground(Color.decode("#708090"));
        btnVoltar.setForeground(Color.white);
    }//GEN-LAST:event_btnVoltarMouseEntered

    private void btnVoltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarMouseExited
        // TODO add your handling code here:
        btnVoltar.setBackground(Color.white);
        btnVoltar.setForeground(Color.black);
    }//GEN-LAST:event_btnVoltarMouseExited

    private void btnPesquisarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarMouseEntered
        // TODO add your handling code here:
        btnPesquisar.setBackground(Color.decode("#708090"));
        btnPesquisar.setForeground(Color.white);
    }//GEN-LAST:event_btnPesquisarMouseEntered

    private void btnPesquisarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarMouseExited
        // TODO add your handling code here:
        btnPesquisar.setBackground(Color.white);
        btnPesquisar.setForeground(Color.black);
    }//GEN-LAST:event_btnPesquisarMouseExited

    private void btnInformacoesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInformacoesMouseEntered
        // TODO add your handling code here:
        btnInformacoes.setBackground(Color.decode("#708090"));
        btnInformacoes.setForeground(Color.white);
    }//GEN-LAST:event_btnInformacoesMouseEntered

    private void btnInformacoesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInformacoesMouseExited
        // TODO add your handling code here:
        btnInformacoes.setBackground(Color.white);
        btnInformacoes.setForeground(Color.black);
    }//GEN-LAST:event_btnInformacoesMouseExited

    private void btnEditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseEntered
        // TODO add your handling code here:
        btnEditar.setBackground(Color.decode("#708090"));
        btnEditar.setForeground(Color.white);
    }//GEN-LAST:event_btnEditarMouseEntered

    private void btnEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseExited
        // TODO add your handling code here:
        btnEditar.setBackground(Color.white);
        btnEditar.setForeground(Color.black);
    }//GEN-LAST:event_btnEditarMouseExited

    private void btnExcluirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirMouseEntered
        // TODO add your handling code here:
        btnExcluir.setBackground(Color.decode("#708090"));
        btnExcluir.setForeground(Color.white);
    }//GEN-LAST:event_btnExcluirMouseEntered

    private void btnExcluirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirMouseExited
        // TODO add your handling code here:
        btnExcluir.setBackground(Color.white);
        btnExcluir.setForeground(Color.black);
    }//GEN-LAST:event_btnExcluirMouseExited

    private void btnAlugarLivroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlugarLivroMouseEntered
        // TODO add your handling code here:
        btnAlugarLivro.setBackground(Color.decode("#708090"));
        btnAlugarLivro.setForeground(Color.white);
    }//GEN-LAST:event_btnAlugarLivroMouseEntered

    private void btnAlugarLivroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlugarLivroMouseExited
        // TODO add your handling code here:
        btnAlugarLivro.setBackground(Color.white);
        btnAlugarLivro.setForeground(Color.black);
    }//GEN-LAST:event_btnAlugarLivroMouseExited
    public void inserirLinhaTabela(Aluno aluno, DefaultTableModel tabela){
        tabela.addRow(new Object[] {aluno.getNome(), String.valueOf(aluno.getMatricula()), aluno.getCurso(), aluno.getCpf(), String.valueOf(aluno.getQuantidadeLivrosAlugados())});
    }
    
    public void limparTabela(){
        DefaultTableModel tabela = (DefaultTableModel) tabelaListaAluno.getModel();
        while(tabela.getRowCount() > 0){
            tabela.removeRow(0);
        }
    }
    
    private void buscarAluno(boolean buscar){
        boolean flagEncontrouAluno = false;
        Aluno aluno = new Aluno();
        String txtDeBusca = this.txtBuscaAluno.getText();
        String matricula;
        String quantidadeLivros;
        int cbxIndex = this.comboBoxBusca.getSelectedIndex();
        DefaultTableModel tabela = (DefaultTableModel) tabelaListaAluno.getModel();
        limparTabela();
        for(int i = 0; i < alunos.quantidadeAlunos(); i++){
            aluno = alunos.getAluno(i);
            if(cbxIndex == 0){
                if(aluno.getNome().toLowerCase().contains(txtDeBusca))
                    inserirLinhaTabela(aluno, tabela);
            }else if(cbxIndex == 1){
                matricula = String.valueOf(aluno.getMatricula());
                if(matricula.contains(txtDeBusca))
                    inserirLinhaTabela(aluno, tabela);
            }else if(cbxIndex == 2){
                quantidadeLivros = String.valueOf(aluno.getQuantidadeLivrosAlugados());
                if(aluno.getQuantidadeLivrosAlugados() > 0)
                    inserirLinhaTabela(aluno, tabela);
            }
        }
        
        if(tabelaListaAluno.getRowCount() == 0 && buscar)
            JOptionPane.showMessageDialog(this, "Nenhum resultado encontrado", "Aluno não Encontrado", JOptionPane.WARNING_MESSAGE);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaPesquisaAluno dialog = new TelaPesquisaAluno(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlugarLivro;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInformacoes;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> comboBoxBusca;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JTable tabelaListaAluno;
    private javax.swing.JTextField txtBuscaAluno;
    // End of variables declaration//GEN-END:variables
}
