/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.biblioteca.view;


import br.com.biblioteca.main.Main;
import static br.com.biblioteca.main.Main.alunos;
import static br.com.biblioteca.main.Main.livros;
import static br.com.biblioteca.main.Main.matriculaSessao;
import br.com.biblioteca.model.Aluno;
import br.com.biblioteca.model.Livro;
import java.awt.Color;
import java.awt.Frame;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rf
 */
public class TelaPesquisaLivroAluno extends javax.swing.JDialog {

    /**
     * Creates new form TelaPesquisaLivro
     */
    private Frame parent;
    public TelaPesquisaLivroAluno(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        buscarLivro(false);
        this.parent = parent;
        this.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        txtBuscaLivro.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        txtBuscaLivro = new javax.swing.JTextField();
        btnInformacoes = new javax.swing.JButton();
        comboBoxBuscaLivro = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaListaLivro = new javax.swing.JTable();
        btnPesquisar = new javax.swing.JButton();
        btnAlugarLivro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        kGradientPanel1.setkEndColor(new java.awt.Color(107, 22, 22));
        kGradientPanel1.setkGradientFocus(250);
        kGradientPanel1.setkStartColor(new java.awt.Color(75, 77, 75));

        jPanel1.setBackground(new java.awt.Color(1, 19, 123));

        jLabel3.setFont(new java.awt.Font("UnPilgi", 1, 48)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Pesquisar Livro");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/biblioteca/images/buscarlivro.png"))); // NOI18N

        btnVoltar.setBackground(new java.awt.Color(255, 255, 255));
        btnVoltar.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/biblioteca/images/back.png"))); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVoltarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVoltarMouseEntered(evt);
            }
        });
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(202, 202, 202)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtBuscaLivro.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        txtBuscaLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscaLivroActionPerformed(evt);
            }
        });
        txtBuscaLivro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscaLivroKeyPressed(evt);
            }
        });

        btnInformacoes.setBackground(new java.awt.Color(255, 255, 255));
        btnInformacoes.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnInformacoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/biblioteca/images/info.png"))); // NOI18N
        btnInformacoes.setText("Informações");
        btnInformacoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInformacoesMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInformacoesMouseEntered(evt);
            }
        });
        btnInformacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformacoesActionPerformed(evt);
            }
        });

        comboBoxBuscaLivro.setBackground(new java.awt.Color(255, 255, 255));
        comboBoxBuscaLivro.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        comboBoxBuscaLivro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Título", "Autor", "ISBN", "Disponíveis" }));
        comboBoxBuscaLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxBuscaLivroActionPerformed(evt);
            }
        });

        tabelaListaLivro.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        tabelaListaLivro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Titulo", "Autor", "ISBN", "Quantidade", "Disponível"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaListaLivro.setRowHeight(30);
        jScrollPane1.setViewportView(tabelaListaLivro);

        btnPesquisar.setBackground(new java.awt.Color(255, 255, 255));
        btnPesquisar.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/biblioteca/images/loupe.png"))); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPesquisarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPesquisarMouseEntered(evt);
            }
        });
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnAlugarLivro.setBackground(new java.awt.Color(255, 255, 255));
        btnAlugarLivro.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnAlugarLivro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/biblioteca/images/emprestimoLivro2.png"))); // NOI18N
        btnAlugarLivro.setText("Alugar Livro");
        btnAlugarLivro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAlugarLivroMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAlugarLivroMouseEntered(evt);
            }
        });
        btnAlugarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlugarLivroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addGap(0, 31, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1018, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnInformacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(btnAlugarLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(282, 282, 282))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(txtBuscaLivro)
                        .addGap(39, 39, 39)
                        .addComponent(comboBoxBuscaLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscaLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxBuscaLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInformacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlugarLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        txtBuscaLivro.setText("");
        dispose();
        this.parent.enable();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void txtBuscaLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscaLivroActionPerformed

    private void txtBuscaLivroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaLivroKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == evt.VK_ENTER)
            buscarLivro(true);
    }//GEN-LAST:event_txtBuscaLivroKeyPressed

    private void btnInformacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformacoesActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = tabelaListaLivro.getSelectedRow();
        if(linhaSelecionada == -1){
            JOptionPane.showMessageDialog(this, "Nenhum Livro Selecionado", "Falha ao Ver as Informações", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Livro livro = new Livro();
        try{
            Object obj = tabelaListaLivro.getValueAt(linhaSelecionada, 2);
            String isbn = String.valueOf(obj);
            livro = livros.getLivroIsbn(isbn);
            TelaInfoEditLivro telaInfoEditLivro = new TelaInfoEditLivro(this.parent, false, livro, false);
            telaInfoEditLivro.setVisible(true);
            telaInfoEditLivro.setLocationRelativeTo(null);
            dispose();
        }catch(NullPointerException ex){
            JOptionPane.showMessageDialog(this, "Erro ao Selecionar o Livro", "Erro", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnInformacoesActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:
        buscarLivro(true);

    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnAlugarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlugarLivroActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = tabelaListaLivro.getSelectedRow();
        if(linhaSelecionada == -1){
            JOptionPane.showMessageDialog(this, "Nenhum Livro Selecionado", "Falha ao Alugar o Livro", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Livro livro = new Livro();
        Aluno aluno = new Aluno();
        try{
            aluno = alunos.getAlunoMatricula(matriculaSessao);
            Object obj = tabelaListaLivro.getValueAt(linhaSelecionada, 2);
            String isbn = String.valueOf(obj);
            livro = livros.getLivroIsbn(isbn);
            TelaSolicitarEmprestimo solicitarEmprestimo = new TelaSolicitarEmprestimo(this.parent, false, aluno, livro);
            solicitarEmprestimo.setVisible(true);
            solicitarEmprestimo.setLocationRelativeTo(null);
            dispose();
        }catch(NullPointerException ex){
            JOptionPane.showMessageDialog(this, "Erro ao Selecionar o Livro", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAlugarLivroActionPerformed

    private void btnVoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarMouseEntered
        // TODO add your handling code here:
        btnVoltar.setBackground(Color.decode("#708090"));
	btnVoltar.setForeground(Color.white);

    }//GEN-LAST:event_btnVoltarMouseEntered

    private void btnVoltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarMouseExited
        // TODO add your handling code here:
        btnVoltar.setBackground(Color.white);
	btnVoltar.setForeground(Color.black);

    }//GEN-LAST:event_btnVoltarMouseExited

    private void btnPesquisarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarMouseEntered
        // TODO add your handling code here:
        btnPesquisar.setBackground(Color.decode("#708090"));
        btnPesquisar.setForeground(Color.white);

    }//GEN-LAST:event_btnPesquisarMouseEntered

    private void btnPesquisarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarMouseExited
        // TODO add your handling code here:
        btnPesquisar.setBackground(Color.white);
        btnPesquisar.setForeground(Color.black);

    }//GEN-LAST:event_btnPesquisarMouseExited

    private void btnInformacoesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInformacoesMouseEntered
        // TODO add your handling code here:
        btnInformacoes.setBackground(Color.decode("#708090"));
        btnInformacoes.setForeground(Color.white);

    }//GEN-LAST:event_btnInformacoesMouseEntered

    private void btnInformacoesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInformacoesMouseExited
        // TODO add your handling code here:
        btnInformacoes.setBackground(Color.white);
        btnInformacoes.setForeground(Color.black);

    }//GEN-LAST:event_btnInformacoesMouseExited

    private void btnAlugarLivroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlugarLivroMouseEntered
        // TODO add your handling code here:
        btnAlugarLivro.setBackground(Color.decode("#708090"));
        btnAlugarLivro.setForeground(Color.white);

    }//GEN-LAST:event_btnAlugarLivroMouseEntered

    private void btnAlugarLivroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlugarLivroMouseExited
        // TODO add your handling code here:
        btnAlugarLivro.setBackground(Color.white);
        btnAlugarLivro.setForeground(Color.black);

    }//GEN-LAST:event_btnAlugarLivroMouseExited

    private void comboBoxBuscaLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxBuscaLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxBuscaLivroActionPerformed

    public void inserirLinhaTabela(Livro livro, DefaultTableModel tabela){  
        tabela.addRow(new String[] {livro.getTitulo(), livro.getAutor(), livro.getIsbn(), String.valueOf(livro.getQuantidade()), String.valueOf(livro.getQuantidadeDisponivel())});
    }
    
    public void limparTabela(){
        DefaultTableModel tabela = (DefaultTableModel) tabelaListaLivro.getModel();
        while(tabela.getRowCount() > 0){
            tabela.removeRow(0);
        }
    }
    
    private void removerLivro(int index){
        int decisaodeExcluir = 0;
        Livro livro = new Livro();
           try{
                Object obj = tabelaListaLivro.getValueAt(index, 2);
                String isbn = String.valueOf(obj);
                livro = livros.getLivroIsbn(isbn);
                decisaodeExcluir = JOptionPane.showOptionDialog(this, "Deseja Realmente Excluir o Livro ", "Decisão de Exclusão", JOptionPane.YES_OPTION, JOptionPane.NO_OPTION, null, null, null);
                if(decisaodeExcluir == 0){
                    livros.removerLivro(livro);
                    JOptionPane.showMessageDialog(this, "Livro Excluido", "Exclusão Efetuada", JOptionPane.INFORMATION_MESSAGE);
                }
           }catch(NullPointerException ex){
               JOptionPane.showMessageDialog(this, "Erro ao Realizar a Exclusão", "Erro", JOptionPane.ERROR_MESSAGE);
           }

           
    }
    
    private void buscarLivro(boolean buscar){
        boolean flagEncontrouLivro = false;
        Livro livro = new Livro();
        String txtDeBusca = this.txtBuscaLivro.getText();
        
        int cbxIndex = this.comboBoxBuscaLivro.getSelectedIndex();
        DefaultTableModel tabela = (DefaultTableModel) tabelaListaLivro.getModel();
        limparTabela();
        for(int i = 0; i < livros.quantidadeLivro(); i++){
            livro = livros.getLivro(i);
            if(cbxIndex == 0){
                if(livro.getTitulo().toLowerCase().contains(txtDeBusca))
                    inserirLinhaTabela(livro, tabela);
            }else if(cbxIndex == 1){
                if(livro.getAutor().toLowerCase().contains(txtDeBusca))
                    inserirLinhaTabela(livro, tabela);
            }else if(cbxIndex == 2){
                if(livro.getIsbn().contains(txtDeBusca))
                    inserirLinhaTabela(livro, tabela);
            }else if(cbxIndex == 3){
                if(livro.getQuantidadeDisponivel() > 0)
                    inserirLinhaTabela(livro, tabela);
            }
        }
         if(tabelaListaLivro.getRowCount() == 0 && buscar)
            JOptionPane.showMessageDialog(this, "Nenhum resultado encontrado", "Livro não Encontrado", JOptionPane.WARNING_MESSAGE);
     }   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisaLivroAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisaLivroAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisaLivroAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisaLivroAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaPesquisaLivroAluno dialog = new TelaPesquisaLivroAluno(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlugarLivro;
    private javax.swing.JButton btnInformacoes;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> comboBoxBuscaLivro;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JTable tabelaListaLivro;
    private javax.swing.JTextField txtBuscaLivro;
    // End of variables declaration//GEN-END:variables
}
