/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.biblioteca.view;

import br.com.biblioteca.main.Main;
import static br.com.biblioteca.main.Main.alunos;
import static br.com.biblioteca.main.Main.bibliotecarias;
import static br.com.biblioteca.main.Main.contaSessao;
import static br.com.biblioteca.main.Main.cpfSessao;
import static br.com.biblioteca.main.Main.matriculaSessao;
import static br.com.biblioteca.main.Main.nomeSessao;
import static br.com.biblioteca.main.Main.usuarioSessao;
import br.com.biblioteca.model.Aluno;
import br.com.biblioteca.model.Bibliotecaria;
import java.awt.Color;

/**
 *
 * @author natannobre
 */
public class TelaHomeAluno extends javax.swing.JFrame {

    /**
     * Creates new form TelaHomeAluno
     */
    public TelaHomeAluno() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        iniciarSessao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnPesquisarLivro = new javax.swing.JButton();
        btnRealizarEmprestimo = new javax.swing.JButton();
        btnPesquisaEmprestimo = new javax.swing.JButton();
        btnVisualizarHistorico = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnSairTelaHome = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblConta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setkEndColor(new java.awt.Color(107, 22, 22));
        kGradientPanel1.setkGradientFocus(250);
        kGradientPanel1.setkStartColor(new java.awt.Color(36, 22, 22));
        kGradientPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                kGradientPanel1MouseMoved(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/biblioteca/images/open-book.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/biblioteca/images/book.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/biblioteca/images/livros.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/biblioteca/images/books.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(75, 193, 193));

        btnPesquisarLivro.setBackground(new java.awt.Color(255, 255, 255));
        btnPesquisarLivro.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnPesquisarLivro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/biblioteca/images/buscarlivro2.png"))); // NOI18N
        btnPesquisarLivro.setText("Pesquisar Livro");
        btnPesquisarLivro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPesquisarLivroMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPesquisarLivroMouseEntered(evt);
            }
        });
        btnPesquisarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarLivroActionPerformed(evt);
            }
        });

        btnRealizarEmprestimo.setBackground(new java.awt.Color(255, 255, 255));
        btnRealizarEmprestimo.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnRealizarEmprestimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/biblioteca/images/emprestimoLivro2.png"))); // NOI18N
        btnRealizarEmprestimo.setText("Realizar Empréstimo");
        btnRealizarEmprestimo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRealizarEmprestimoMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRealizarEmprestimoMouseEntered(evt);
            }
        });
        btnRealizarEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarEmprestimoActionPerformed(evt);
            }
        });

        btnPesquisaEmprestimo.setBackground(new java.awt.Color(255, 255, 255));
        btnPesquisaEmprestimo.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnPesquisaEmprestimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/biblioteca/images/buscaemprestimo2.png"))); // NOI18N
        btnPesquisaEmprestimo.setText("Meus Empréstimos");
        btnPesquisaEmprestimo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPesquisaEmprestimoMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPesquisaEmprestimoMouseEntered(evt);
            }
        });
        btnPesquisaEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaEmprestimoActionPerformed(evt);
            }
        });

        btnVisualizarHistorico.setBackground(new java.awt.Color(255, 255, 255));
        btnVisualizarHistorico.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnVisualizarHistorico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/biblioteca/images/folder2.png"))); // NOI18N
        btnVisualizarHistorico.setText("Visualizar Histórico");
        btnVisualizarHistorico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVisualizarHistoricoMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVisualizarHistoricoMouseEntered(evt);
            }
        });
        btnVisualizarHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarHistoricoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnPesquisarLivro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnRealizarEmprestimo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPesquisaEmprestimo, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
            .addComponent(btnVisualizarHistorico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnPesquisarLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRealizarEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPesquisaEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVisualizarHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setBackground(new java.awt.Color(26, 14, 143));
        jLabel3.setFont(new java.awt.Font("UnPilgi", 1, 48)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Sistema de Biblioteca");

        btnSairTelaHome.setBackground(java.awt.Color.white);
        btnSairTelaHome.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnSairTelaHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/biblioteca/images/exit.png"))); // NOI18N
        btnSairTelaHome.setText("Sair");
        btnSairTelaHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSairTelaHomeMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSairTelaHomeMouseEntered(evt);
            }
        });
        btnSairTelaHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairTelaHomeActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/biblioteca/images/user.png"))); // NOI18N
        jLabel1.setToolTipText("");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("Usuário:");

        lblUsuario.setForeground(java.awt.Color.white);
        lblUsuario.setText("Usuário:");

        lblNome.setForeground(java.awt.Color.white);
        lblNome.setText("Nome:");

        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setText("Nome:");

        jLabel11.setForeground(java.awt.Color.white);
        jLabel11.setText("Conta:");

        lblConta.setForeground(java.awt.Color.white);
        lblConta.setText("Conta:");

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(185, 185, 185)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addGap(444, 444, 444)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addGap(128, 128, 128)
                                        .addComponent(jLabel5)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(114, 114, 114)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(4, 4, 4))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                                        .addGap(591, 591, 591)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblConta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(9, 9, 9))))
                            .addComponent(jLabel1))
                        .addGap(20, 20, 20))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(128, 128, 128)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(btnSairTelaHome, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(6, 6, 6)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblConta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSairTelaHome)
                        .addGap(492, 492, 492))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)))))
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarLivroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarLivroMouseExited
        // TODO add your handling code here:
        btnPesquisarLivro.setBackground(Color.white);
        btnPesquisarLivro.setForeground(Color.black);
    }//GEN-LAST:event_btnPesquisarLivroMouseExited

    private void btnPesquisarLivroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarLivroMouseEntered
        // TODO add your handling code here:
        btnPesquisarLivro.setBackground(Color.decode("#708090"));
        btnPesquisarLivro.setForeground(Color.white);
    }//GEN-LAST:event_btnPesquisarLivroMouseEntered

    private void btnPesquisarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarLivroActionPerformed
        // TODO add your handling code here:
        TelaPesquisaLivroAluno pesquisaLivroAluno = new TelaPesquisaLivroAluno(this, false);
        pesquisaLivroAluno.setVisible(true);
        pesquisaLivroAluno.setLocationRelativeTo(null);
        this.setEnabled(false);
    }//GEN-LAST:event_btnPesquisarLivroActionPerformed

    private void btnRealizarEmprestimoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRealizarEmprestimoMouseExited
        // TODO add your handling code here:
        btnRealizarEmprestimo.setBackground(Color.white);
        btnRealizarEmprestimo.setForeground(Color.black);
    }//GEN-LAST:event_btnRealizarEmprestimoMouseExited

    private void btnRealizarEmprestimoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRealizarEmprestimoMouseEntered
        // TODO add your handling code here:
        btnRealizarEmprestimo.setBackground(Color.decode("#708090"));
        btnRealizarEmprestimo.setForeground(Color.white);
    }//GEN-LAST:event_btnRealizarEmprestimoMouseEntered

    private void btnRealizarEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarEmprestimoActionPerformed
        // TODO add your handling code here:
        Aluno aluno = new Aluno();
        aluno = alunos.getAlunoMatricula(matriculaSessao);
        TelaSolicitarEmprestimo solicitarEmprestimo = new TelaSolicitarEmprestimo(this, false, aluno);
        solicitarEmprestimo.setVisible(true);
        solicitarEmprestimo.setLocationRelativeTo(null);
        this.setEnabled(false);
    }//GEN-LAST:event_btnRealizarEmprestimoActionPerformed

    private void btnPesquisaEmprestimoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisaEmprestimoMouseExited
        // TODO add your handling code here:
        btnPesquisaEmprestimo.setBackground(Color.white);
        btnPesquisaEmprestimo.setForeground(Color.black);
    }//GEN-LAST:event_btnPesquisaEmprestimoMouseExited

    private void btnPesquisaEmprestimoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisaEmprestimoMouseEntered
        // TODO add your handling code here:
        btnPesquisaEmprestimo.setBackground(Color.decode("#708090"));
        btnPesquisaEmprestimo.setForeground(Color.white);
    }//GEN-LAST:event_btnPesquisaEmprestimoMouseEntered

    private void btnPesquisaEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaEmprestimoActionPerformed
        // TODO add your handling code here:
        TelaMeusEmprestimos meusEmprestimo = new TelaMeusEmprestimos(this, false);
        meusEmprestimo.setVisible(true);
        meusEmprestimo.setLocationRelativeTo(null);
        this.setEnabled(false);
    }//GEN-LAST:event_btnPesquisaEmprestimoActionPerformed

    private void btnVisualizarHistoricoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVisualizarHistoricoMouseExited
        // TODO add your handling code here:
        btnVisualizarHistorico.setBackground(Color.white);
        btnVisualizarHistorico.setForeground(Color.black);
    }//GEN-LAST:event_btnVisualizarHistoricoMouseExited

    private void btnVisualizarHistoricoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVisualizarHistoricoMouseEntered
        // TODO add your handling code here:
        btnVisualizarHistorico.setBackground(Color.decode("#708090"));
        btnVisualizarHistorico.setForeground(Color.white);
    }//GEN-LAST:event_btnVisualizarHistoricoMouseEntered

    private void btnVisualizarHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarHistoricoActionPerformed
        // TODO add your handling code here:
        Aluno aluno = new Aluno();
        aluno = alunos.getAlunoMatricula(matriculaSessao);
        TelaVisualizarHistorico visualizarHistorico = new TelaVisualizarHistorico(this, false, aluno);
        visualizarHistorico.setVisible(true);
        visualizarHistorico.setLocationRelativeTo(null);
        this.setEnabled(false);
    }//GEN-LAST:event_btnVisualizarHistoricoActionPerformed

    private void btnSairTelaHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairTelaHomeMouseExited
        // TODO add your handling code here:
        btnSairTelaHome.setBackground(Color.white);
        btnSairTelaHome.setForeground(Color.black);
    }//GEN-LAST:event_btnSairTelaHomeMouseExited

    private void btnSairTelaHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairTelaHomeMouseEntered
        // TODO add your handling code here:
        btnSairTelaHome.setBackground(Color.decode("#708090"));
        btnSairTelaHome.setForeground(Color.white);
    }//GEN-LAST:event_btnSairTelaHomeMouseEntered

    private void btnSairTelaHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairTelaHomeActionPerformed
        // TODO add your handling code here:
        destruirSessao();
        TelaLogin telaLogin = new TelaLogin();
        telaLogin.setVisible(true);
        dispose();

    }//GEN-LAST:event_btnSairTelaHomeActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        Aluno aluno = new Aluno();
        aluno = alunos.getAlunoMatricula(matriculaSessao);
        TelaInfoEditAluno telaInfoEditAluno = new TelaInfoEditAluno(this, false, aluno, true, true);
        telaInfoEditAluno.setVisible(true);
        telaInfoEditAluno.setLocationRelativeTo(null);
        this.setEnabled(false);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void kGradientPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel1MouseMoved
        // TODO add your handling code here:
        //liberarBotoes();
    }//GEN-LAST:event_kGradientPanel1MouseMoved

    public void destruirSessao(){
        nomeSessao = "";
        usuarioSessao = "";
        contaSessao = "";
        cpfSessao = "";
    }
    
    public void iniciarSessao(){
  
        lblUsuario.setText(usuarioSessao);
        lblNome.setText(nomeSessao);
        lblConta.setText(contaSessao);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaHomeAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaHomeAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaHomeAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaHomeAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaHomeAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesquisaEmprestimo;
    private javax.swing.JButton btnPesquisarLivro;
    private javax.swing.JButton btnRealizarEmprestimo;
    private javax.swing.JButton btnSairTelaHome;
    private javax.swing.JButton btnVisualizarHistorico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lblConta;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables
}
