/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.biblioteca.view;

import static br.com.biblioteca.main.Main.alunos;
import static br.com.biblioteca.main.Main.usuarioSessao;
import br.com.biblioteca.model.Aluno;
import java.awt.Color;
import java.awt.Frame;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author rf
 */
public class TelaInfoEditAluno extends javax.swing.JDialog {

    /**
     * Creates new form TelaInfoEditAluno
     * 
     *
     */
    private Aluno aluno;
    private Frame parent;
    private boolean isPerfil;
    
    public TelaInfoEditAluno(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public TelaInfoEditAluno(java.awt.Frame parent, boolean modal, Aluno aluno, boolean edit, boolean isPerfil) {
        super(parent, modal);
        initComponents();
        this.parent = parent;
        txtCPFInfoAluno.setFont(new java.awt.Font("Ubuntu", 0, 18));
        txtTelefoneInfoAluno.setFont(new java.awt.Font("Ubuntu", 0, 18));
        txtMatriculaInfoAluno.setFont(new java.awt.Font("Ubuntu", 0, 18));
        txtDataNascInfoAluno.setFont(new java.awt.Font("Ubuntu", 0, 18));
        inicializaCampos(aluno);
        this.aluno = aluno;
        if(!edit){
            bloqueiaCampos();
        }
        this.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        this.isPerfil = isPerfil;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNomeInfoAluno = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCursoInfoAluno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCPFInfoAluno = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTelefoneInfoAluno = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        txtMatriculaInfoAluno = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDataNascInfoAluno = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        txtUsuarioInfoAluno = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtSenhaInfoAluno = new javax.swing.JPasswordField();
        btnSalvar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtLivrosInfoAluno = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        kGradientPanel1.setkEndColor(new java.awt.Color(107, 22, 22));
        kGradientPanel1.setkGradientFocus(250);
        kGradientPanel1.setkStartColor(new java.awt.Color(75, 77, 75));

        jPanel1.setBackground(new java.awt.Color(1, 19, 123));

        jLabel3.setFont(new java.awt.Font("UnPilgi", 1, 48)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Informações do Aluno");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/biblioteca/images/user2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jLabel3)
                .addGap(27, 27, 27)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGap(16, 16, 16))
        );

        txtNomeInfoAluno.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        txtNomeInfoAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeInfoAlunoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Nome:");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Curso:");

        txtCursoInfoAluno.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        txtCursoInfoAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCursoInfoAlunoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("CPF:");

        txtCPFInfoAluno.setBackground(new java.awt.Color(255, 255, 255));
        try {
            txtCPFInfoAluno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Telefone:");

        try {
            txtTelefoneInfoAluno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("Matricula:");

        try {
            txtMatriculaInfoAluno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel8.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("Data de Nascimento:");

        txtDataNascInfoAluno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        jLabel9.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setText("Usuário:");

        txtUsuarioInfoAluno.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        txtUsuarioInfoAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioInfoAlunoActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setText("Senha:");

        txtSenhaInfoAluno.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        btnSalvar.setBackground(new java.awt.Color(255, 255, 255));
        btnSalvar.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/biblioteca/images/export.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalvarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalvarMouseEntered(evt);
            }
        });
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnVoltar.setBackground(new java.awt.Color(255, 255, 255));
        btnVoltar.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/biblioteca/images/cancel.png"))); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVoltarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVoltarMouseEntered(evt);
            }
        });
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel11.setForeground(java.awt.Color.white);
        jLabel11.setText("Livros:");

        txtLivrosInfoAluno.setEditable(false);
        txtLivrosInfoAluno.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(40, 40, 40)))
                        .addGap(12, 12, 12)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(txtCPFInfoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTelefoneInfoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11))
                            .addComponent(txtNomeInfoAluno)))
                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtLivrosInfoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel2)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                    .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                    .addComponent(txtMatriculaInfoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtDataNascInfoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtSenhaInfoAluno)
                                .addComponent(txtUsuarioInfoAluno)
                                .addComponent(txtCursoInfoAluno)))))
                .addGap(68, 68, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNomeInfoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCPFInfoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefoneInfoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel11)
                    .addComponent(txtLivrosInfoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMatriculaInfoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(txtDataNascInfoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCursoInfoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtUsuarioInfoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSenhaInfoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeInfoAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeInfoAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeInfoAlunoActionPerformed

    private void txtCursoInfoAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCursoInfoAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCursoInfoAlunoActionPerformed

    private void txtUsuarioInfoAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioInfoAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioInfoAlunoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        String nome = txtNomeInfoAluno.getText();
        String cpf = txtCPFInfoAluno.getText();
        String telefone = txtTelefoneInfoAluno.getText();
        String matricula = txtMatriculaInfoAluno.getText();
        String dataNasc = txtDataNascInfoAluno.getText();
        String curso = txtCursoInfoAluno.getText();
        String usuario = txtUsuarioInfoAluno.getText();
        String senha = txtSenhaInfoAluno.getText();
        String quantidadeLivros = txtLivrosInfoAluno.getText();
        boolean testeCampos = true;
        boolean alterarLabel = false;

        if(nome.equals("")){
            testeCampos = false;
            txtNomeInfoAluno.setBackground(Color.decode("#FF6347"));
        }
        if(cpf.equals("   .   .   -  ")){
            testeCampos = false;
            txtCPFInfoAluno.setBackground(Color.decode("#FF6347"));
        }
        if(telefone.equals("(  )      -    ")){
            testeCampos = false;
            txtTelefoneInfoAluno.setBackground(Color.decode("#FF6347"));

        }
        if(matricula.equals("      ")){
            testeCampos = false;
            txtMatriculaInfoAluno.setBackground(Color.decode("#FF6347"));
        }
        if(dataNasc.equals("")){
            testeCampos = false;
            txtDataNascInfoAluno.setBackground(Color.decode("#FF6347"));
        }
        if(curso.equals("")){
            testeCampos = false;
            txtCursoInfoAluno.setBackground(Color.decode("#FF6347"));
        }
        if(usuario.equals("")){
            testeCampos = false;
            txtUsuarioInfoAluno.setBackground(Color.decode("#FF6347"));
        }
        if(senha.equals("")){
            testeCampos = false;
            txtSenhaInfoAluno.setBackground(Color.decode("#FF6347"));
        }

        if(!testeCampos){
            JOptionPane.showMessageDialog(this, "Preencha todos os campos obrigatórios", "Erro ao Atualizar", JOptionPane.ERROR_MESSAGE);
            txtNomeInfoAluno.requestFocus();
            pintarCampos();
            return;
        }

        int matrciula_aluno = Integer.parseInt(matricula);
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate dataNascimento = LocalDate.parse(dataNasc, formato);
     
        if(alunos.alunoJaCadastrado(usuario, matrciula_aluno, this.aluno)){
            JOptionPane.showMessageDialog(this, "Registro já Encontrado", "Erro ao Atualizar Cadastro", JOptionPane.ERROR_MESSAGE);
            limparCampos();
            txtNomeInfoAluno.requestFocus();
            inicializaCampos(aluno);
            return;
        }
        
        if(aluno.getUsuario().equals(usuarioSessao)){
            alterarLabel = true;
        }
        
        aluno.setNome(nome);
        aluno.setCpf(cpf);
        aluno.setDataNascimento(dataNascimento);
        aluno.setTelefone(telefone);
        aluno.setMatricula(matrciula_aluno);
        aluno.setCurso(curso);
        aluno.setUsuario(usuario);
        aluno.setSenha(senha);
        
        JOptionPane.showMessageDialog(this, "Aluno Atualizado com Sucesso", "Alteração Realizada", JOptionPane.INFORMATION_MESSAGE);
         
        limparCampos();
        if(!isPerfil){
            TelaPesquisaAluno pesquisaAluno = new TelaPesquisaAluno(this.parent, false);
            pesquisaAluno.setVisible(true);
            pesquisaAluno.setLocationRelativeTo(null);
        }
        dispose();
        this.parent.enable();
        if(alterarLabel){
            TelaLogin login = new TelaLogin();
            login.loginGuest(aluno.getUsuario(), aluno.getSenha(), 0);
            this.parent.dispose();
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        limparCampos();
        if(!this.isPerfil){
            TelaPesquisaAluno pesquisaAluno = new TelaPesquisaAluno(this.parent, false);
            pesquisaAluno.setVisible(true);
            pesquisaAluno.setLocationRelativeTo(null);
        }
        dispose();
        this.parent.enable();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnVoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarMouseEntered
        // TODO add your handling code here:
        btnVoltar.setBackground(Color.decode("#708090"));
        btnVoltar.setForeground(Color.white);
    }//GEN-LAST:event_btnVoltarMouseEntered

    private void btnVoltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarMouseExited
        // TODO add your handling code here:
        btnVoltar.setBackground(Color.white);
        btnVoltar.setForeground(Color.black);
    }//GEN-LAST:event_btnVoltarMouseExited

    private void btnSalvarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseEntered
        // TODO add your handling code here:
        btnSalvar.setBackground(Color.decode("#708090"));
        btnSalvar.setForeground(Color.white);
        
    }//GEN-LAST:event_btnSalvarMouseEntered

    private void btnSalvarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseExited
        // TODO add your handling code here:
        btnSalvar.setBackground(Color.white);
        btnSalvar.setForeground(Color.black);
    }//GEN-LAST:event_btnSalvarMouseExited

     public void limparCampos(){
        txtNomeInfoAluno.setText("");
        txtCPFInfoAluno.setText("");
        txtTelefoneInfoAluno.setText("");
        txtMatriculaInfoAluno.setText("");
        txtDataNascInfoAluno.setText("");
        txtCursoInfoAluno.setText("");
        txtUsuarioInfoAluno.setText("");
        txtSenhaInfoAluno.setText("");
    }
    
    public void pintarCampos(){
        txtNomeInfoAluno.setBackground(Color.WHITE);
        txtCPFInfoAluno.setBackground(Color.WHITE);
        txtTelefoneInfoAluno.setBackground(Color.WHITE);
        txtMatriculaInfoAluno.setBackground(Color.WHITE);
        txtDataNascInfoAluno.setBackground(Color.WHITE);
        txtCursoInfoAluno.setBackground(Color.WHITE);
        txtUsuarioInfoAluno.setBackground(Color.WHITE);
        txtSenhaInfoAluno.setBackground(Color.WHITE);
    }
    
    public void inicializaCampos(Aluno aluno){
        txtNomeInfoAluno.setText(aluno.getNome());
        txtCPFInfoAluno.setText(aluno.getCpf());
        txtTelefoneInfoAluno.setText(aluno.getTelefone());
        txtLivrosInfoAluno.setText(String.valueOf(aluno.getQuantidadeLivrosAlugados()));
        txtMatriculaInfoAluno.setText(String.valueOf(aluno.getMatricula()));
        txtCursoInfoAluno.setText(aluno.getCurso());
        txtUsuarioInfoAluno.setText(aluno.getUsuario());
        txtSenhaInfoAluno.setText(aluno.getSenha());
        
        String data = String.valueOf(aluno.getDataNascimento());
        String camposData[] = data.split("-");
        String dataNascimento = camposData[2]+"/"+camposData[1]+"/"+camposData[0];
        txtDataNascInfoAluno.setText(dataNascimento);
    }
    
    public void bloqueiaCampos(){
        txtNomeInfoAluno.setEditable(false);
        txtCPFInfoAluno.setEditable(false);
        txtTelefoneInfoAluno.setEditable(false);
        txtMatriculaInfoAluno.setEditable(false);
        txtDataNascInfoAluno.setEditable(false);
        txtCursoInfoAluno.setEditable(false);
        txtUsuarioInfoAluno.setEditable(false);
        txtSenhaInfoAluno.setEditable(false);
        btnSalvar.setEnabled(false);
       
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInfoEditAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInfoEditAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInfoEditAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInfoEditAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaInfoEditAluno dialog = new TelaInfoEditAluno(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JFormattedTextField txtCPFInfoAluno;
    private javax.swing.JTextField txtCursoInfoAluno;
    private javax.swing.JFormattedTextField txtDataNascInfoAluno;
    private javax.swing.JTextField txtLivrosInfoAluno;
    private javax.swing.JFormattedTextField txtMatriculaInfoAluno;
    private javax.swing.JTextField txtNomeInfoAluno;
    private javax.swing.JPasswordField txtSenhaInfoAluno;
    private javax.swing.JFormattedTextField txtTelefoneInfoAluno;
    private javax.swing.JTextField txtUsuarioInfoAluno;
    // End of variables declaration//GEN-END:variables
}
