/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.biblioteca.view;


import static br.com.biblioteca.main.Main.contaSessao;
import static br.com.biblioteca.main.Main.livros;
import br.com.biblioteca.model.Livro;
import java.awt.Color;
import java.awt.Frame;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author rf
 */
public class TelaInfoEditLivro extends javax.swing.JDialog {

    /**
     * Creates new form TelaInfoEditLivro
     */
    String localImagem = null;
    String nomeImagem =  null;
    boolean imagemSelecionada = false;
    
    private Livro livro;
    private Frame parent;
    
    public TelaInfoEditLivro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
    }
    
    public TelaInfoEditLivro(java.awt.Frame parent, boolean modal, Livro livro, boolean edit) {
        super(parent, modal);
        initComponents();
        this.parent = parent;
        this.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        
        txtISBNInfoLivro.setFont(new java.awt.Font("Ubuntu", 0, 18));
        inicializaCampos(livro);
        this.livro = livro;
        if(!edit){
            bloqueiaCampos();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTituloInfoLivro = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtISBNInfoLivro = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        txtAutorInfoLivro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtQuantidadeInfoLivro = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescricaoInfoLivro = new javax.swing.JTextArea();
        lblImagem = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDisponivelInfoLivro = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        kGradientPanel1.setkEndColor(new java.awt.Color(107, 22, 22));
        kGradientPanel1.setkGradientFocus(250);
        kGradientPanel1.setkStartColor(new java.awt.Color(75, 77, 75));

        jPanel1.setBackground(new java.awt.Color(1, 19, 123));

        jLabel3.setFont(new java.awt.Font("UnPilgi", 1, 48)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Informações do Livro");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/biblioteca/images/addlivro.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addContainerGap(135, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGap(20, 20, 20))
        );

        txtTituloInfoLivro.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        txtTituloInfoLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloInfoLivroActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Título:");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("ISBN:");

        txtISBNInfoLivro.setBackground(new java.awt.Color(255, 255, 255));
        try {
            txtISBNInfoLivro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-##-###-####-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Quantidade:");

        jLabel9.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setText("Descrição:");

        btnSalvar.setBackground(new java.awt.Color(255, 255, 255));
        btnSalvar.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/biblioteca/images/export.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalvarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalvarMouseEntered(evt);
            }
        });
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnVoltar.setBackground(new java.awt.Color(255, 255, 255));
        btnVoltar.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/biblioteca/images/cancel.png"))); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVoltarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVoltarMouseEntered(evt);
            }
        });
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        txtAutorInfoLivro.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        txtAutorInfoLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAutorInfoLivroActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Autor:");

        txtQuantidadeInfoLivro.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        txtQuantidadeInfoLivro.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        txtDescricaoInfoLivro.setColumns(20);
        txtDescricaoInfoLivro.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        txtDescricaoInfoLivro.setRows(5);
        jScrollPane1.setViewportView(txtDescricaoInfoLivro);

        lblImagem.setBackground(new java.awt.Color(255, 255, 255));
        lblImagem.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblImagem.setForeground(java.awt.Color.white);
        lblImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/biblioteca/images/plus3.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setText("Imagem:");

        jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("Disponível:");

        txtDisponivelInfoLivro.setEditable(false);
        txtDisponivelInfoLivro.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(6, 6, 6)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(lblImagem)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtAutorInfoLivro, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTituloInfoLivro)
                    .addComponent(jScrollPane1)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(txtISBNInfoLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQuantidadeInfoLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txtDisponivelInfoLivro)))
                .addGap(75, 75, 75))
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTituloInfoLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAutorInfoLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtISBNInfoLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel6)
                        .addComponent(txtQuantidadeInfoLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addComponent(txtDisponivelInfoLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel10))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTituloInfoLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloInfoLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloInfoLivroActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        String titulo = txtTituloInfoLivro.getText();
        String autor = txtAutorInfoLivro.getText();
        String isbn = txtISBNInfoLivro.getText();
        String descricao = txtDescricaoInfoLivro.getText();
        String quantidade = String.valueOf(txtQuantidadeInfoLivro.getValue());

        boolean testeCampos = true;

        if(titulo.equals("")){
            testeCampos = false;
            txtTituloInfoLivro.setBackground(Color.decode("#FF6347"));
        }
        if(autor.equals("")){
            testeCampos = false;
            txtAutorInfoLivro.setBackground(Color.decode("#FF6347"));
        }
        if(isbn.equals("   -  -   -    - ")){
            testeCampos = false;
            txtISBNInfoLivro.setBackground(Color.decode("#FF6347"));
        }
        if(descricao.equals("")){
            testeCampos = false;
            txtDescricaoInfoLivro.setBackground(Color.decode("#FF6347"));
        }

        int quantidadeLivro = Integer.parseInt(quantidade);

        if(quantidadeLivro == 0){
            testeCampos = false;
            txtQuantidadeInfoLivro.setBackground(Color.decode("#FF6347"));
        }
        if(!testeCampos){
            JOptionPane.showMessageDialog(this, "Preencha todos os campos obrigatórios", "Erro ao realizar o cadastro", JOptionPane.ERROR_MESSAGE);
            //pintarCampos();
            return;
        }
        
        
//        String caminho = getClass().getResource("../images/").toString().substring(5);
//        Icon livroImage = lblImagem.getIcon();
//        System.out.println(caminho);
//        File outputfile = new File(caminho+nomeImagem);
//        BufferedImage image = null;
//        System.out.println(localImagem);
//
//        try {
//            File arquivo1 = new File(localImagem);
//            image = ImageIO.read(arquivo1);
//            ImageIO.write(image, "png", outputfile);
//        } catch (IOException ex) {
//            Logger.getLogger(TelaCadastroLivro.class.getName()).log(Level.SEVERE, null, ex);
//        }
        
        
        if(livros.livroJaCadastrado(isbn, livro)){
            JOptionPane.showMessageDialog(this, "Registro já Encontrado", "Erro ao Realizar Atualização", JOptionPane.ERROR_MESSAGE);
            limparCampos();
            txtTituloInfoLivro.requestFocus();
            inicializaCampos(livro);
            return;
        }
        
        
        livro.setTitulo(titulo);
        livro.setAutor(autor);
        livro.setIsbn(isbn);
        livro.setQuantidade(quantidadeLivro);
        livro.setDescricao(descricao);
        livro.setImagemLivro(livro.getImagemLivro());
        livro.setNomeImagem(nomeImagem);;
        livro.setDisponivel(livro.getQuantidade() - 1);

        JOptionPane.showMessageDialog(this, "Livro Atualizado com Sucesso", "Alteração realizada", JOptionPane.INFORMATION_MESSAGE);
        limparCampos();
        TelaPesquisaLivro pesquisaLivro = new TelaPesquisaLivro(this.parent, false);
        pesquisaLivro.setVisible(true);
        pesquisaLivro.setLocationRelativeTo(null);
        dispose();

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        limparCampos();
        if(contaSessao.equals("Aluno")){
            TelaPesquisaLivroAluno pesquisaLivroAluno = new TelaPesquisaLivroAluno(this.parent, false);
            pesquisaLivroAluno.setVisible(true);
            pesquisaLivroAluno.setLocationRelativeTo(null);
        }else{
            TelaPesquisaLivro pesquisaLivro = new TelaPesquisaLivro(this.parent, false);
            pesquisaLivro.setVisible(true);
            pesquisaLivro.setLocationRelativeTo(null);
        }
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void txtAutorInfoLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAutorInfoLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAutorInfoLivroActionPerformed

    private void btnVoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarMouseEntered
        // TODO add your handling code here:
        btnVoltar.setBackground(Color.decode("#708090"));
        btnVoltar.setForeground(Color.white);
    }//GEN-LAST:event_btnVoltarMouseEntered

    private void btnVoltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarMouseExited
        // TODO add your handling code here:
        btnVoltar.setBackground(Color.white);
        btnVoltar.setForeground(Color.black);
    }//GEN-LAST:event_btnVoltarMouseExited

    private void btnSalvarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseEntered
        // TODO add your handling code here:
        btnSalvar.setBackground(Color.decode("#708090"));
        btnSalvar.setForeground(Color.white);
    }//GEN-LAST:event_btnSalvarMouseEntered

    private void btnSalvarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseExited
        // TODO add your handling code here:
        btnSalvar.setBackground(Color.white);
        btnSalvar.setForeground(Color.black);
    }//GEN-LAST:event_btnSalvarMouseExited

    private void inicializaCampos(Livro livro){
        txtTituloInfoLivro.setText(livro.getTitulo());
        txtAutorInfoLivro.setText(livro.getAutor());
        txtISBNInfoLivro.setText(livro.getIsbn());
        txtQuantidadeInfoLivro.setValue(livro.getQuantidade());
        txtDisponivelInfoLivro.setText(String.valueOf(livro.getQuantidadeDisponivel()));
        txtDescricaoInfoLivro.setText(livro.getDescricao());
        lblImagem.setIcon(livro.getImagemLivro());
        this.nomeImagem = nomeImagem;
        this.localImagem = getClass().getResource("../images/").toString().substring(5);
    }
    
    private void bloqueiaCampos(){
        txtTituloInfoLivro.setEditable(false);
        txtAutorInfoLivro.setEditable(false);
        txtISBNInfoLivro.setEditable(false);
        txtQuantidadeInfoLivro.setEnabled(false);
        txtDescricaoInfoLivro.setEditable(false);
        //lblImagem.setEnabled(false);
        btnSalvar.setEnabled(false);
    }
    
    private void limparCampos(){
        txtTituloInfoLivro.setText("");
        txtAutorInfoLivro.setText("");
        txtISBNInfoLivro.setText("");
        txtQuantidadeInfoLivro.setValue(0);
        txtDescricaoInfoLivro.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInfoEditLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInfoEditLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInfoEditLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInfoEditLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaInfoEditLivro dialog = new TelaInfoEditLivro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JTextField txtAutorInfoLivro;
    private javax.swing.JTextArea txtDescricaoInfoLivro;
    private javax.swing.JTextField txtDisponivelInfoLivro;
    private javax.swing.JFormattedTextField txtISBNInfoLivro;
    private javax.swing.JSpinner txtQuantidadeInfoLivro;
    private javax.swing.JTextField txtTituloInfoLivro;
    // End of variables declaration//GEN-END:variables
}
