/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.biblioteca.view;

import br.com.biblioteca.DAO.AlunoDAOImple;
import br.com.biblioteca.DAO.BibliotecariaDAOImple;
import br.com.biblioteca.DAO.EmprestimoDAOImple;
import br.com.biblioteca.DAO.LivroDAOImple;
import br.com.biblioteca.main.Main;
import static br.com.biblioteca.main.Main.alunos;
import static br.com.biblioteca.main.Main.bibliotecarias;
import static br.com.biblioteca.main.Main.contaSessao;
import static br.com.biblioteca.main.Main.cpfSessao;
import static br.com.biblioteca.main.Main.usuarioSessao;
import static br.com.biblioteca.main.Main.nomeSessao;
import static br.com.biblioteca.main.Main.matriculaSessao;
import br.com.biblioteca.model.Aluno;
import br.com.biblioteca.model.Bibliotecaria;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author rf
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
    
    */
     
    public TelaLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsuarioTelaLogin = new javax.swing.JTextField();
        txtSenhaTelaLogin = new javax.swing.JPasswordField();
        btnEntrar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboBoxTipoConta = new javax.swing.JComboBox<>();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        kGradientPanel1.setkEndColor(new java.awt.Color(107, 22, 22));
        kGradientPanel1.setkGradientFocus(250);
        kGradientPanel1.setkStartColor(new java.awt.Color(75, 77, 75));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Usuário:");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Senha:");

        txtUsuarioTelaLogin.setBackground(new java.awt.Color(255, 255, 255));
        txtUsuarioTelaLogin.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        txtUsuarioTelaLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioTelaLoginActionPerformed(evt);
            }
        });
        txtUsuarioTelaLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsuarioTelaLoginKeyPressed(evt);
            }
        });

        txtSenhaTelaLogin.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        txtSenhaTelaLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSenhaTelaLoginKeyPressed(evt);
            }
        });

        btnEntrar.setBackground(new java.awt.Color(255, 255, 255));
        btnEntrar.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/biblioteca/images/enter.png"))); // NOI18N
        btnEntrar.setText("Entrar");
        btnEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEntrarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEntrarMouseEntered(evt);
            }
        });
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        btnSair.setBackground(new java.awt.Color(255, 255, 255));
        btnSair.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/biblioteca/images/exit.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSairMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSairMouseEntered(evt);
            }
        });
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(1, 19, 123));

        jLabel3.setFont(new java.awt.Font("UnPilgi", 1, 48)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Sistema de Biblioteca");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/biblioteca/images/bookopen.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(25, 25, 25))))
        );

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Tipo de Conta:");

        comboBoxTipoConta.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        comboBoxTipoConta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aluno", "Bibliotecária" }));
        comboBoxTipoConta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                comboBoxTipoContaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(txtUsuarioTelaLogin)
                    .addComponent(jLabel2)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtSenhaTelaLogin)
                    .addComponent(comboBoxTipoConta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtUsuarioTelaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSenhaTelaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBoxTipoConta, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        // TODO add your handling code here:
        realizarLogin();
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void limparCampos(){
        txtUsuarioTelaLogin.setText("");
        txtSenhaTelaLogin.setText("");
        txtUsuarioTelaLogin.requestFocus();
    }
    
    private void txtUsuarioTelaLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioTelaLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioTelaLoginActionPerformed

    private void txtUsuarioTelaLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioTelaLoginKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode() == evt.VK_ENTER)
             txtSenhaTelaLogin.requestFocus();
    }//GEN-LAST:event_txtUsuarioTelaLoginKeyPressed

    private void txtSenhaTelaLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenhaTelaLoginKeyPressed
        // TODO add your handling code here:
      if(evt.getKeyCode() == evt.VK_ENTER)
             comboBoxTipoConta.requestFocus();
    }//GEN-LAST:event_txtSenhaTelaLoginKeyPressed

    private void comboBoxTipoContaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboBoxTipoContaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == evt.VK_ENTER)
             btnEntrar.requestFocus();
    }//GEN-LAST:event_comboBoxTipoContaKeyPressed

    private void btnSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseEntered
        // TODO add your handling code here:
        btnSair.setBackground(Color.decode("#708090"));
        btnSair.setForeground(Color.white);
    }//GEN-LAST:event_btnSairMouseEntered

    private void btnSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseExited
        // TODO add your handling code here:
        btnSair.setBackground(Color.white);
        btnSair.setForeground(Color.black);
    }//GEN-LAST:event_btnSairMouseExited

    private void btnEntrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrarMouseEntered
        // TODO add your handling code here:
        btnEntrar.setBackground(Color.decode("#708090"));
        btnEntrar.setForeground(Color.white);
    }//GEN-LAST:event_btnEntrarMouseEntered

    private void btnEntrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrarMouseExited
        // TODO add your handling code here:
        btnEntrar.setBackground(Color.white);
        btnEntrar.setForeground(Color.black);
    }//GEN-LAST:event_btnEntrarMouseExited

    private void realizarLogin(){
        String usuario = txtUsuarioTelaLogin.getText();
        String senha = txtSenhaTelaLogin.getText();
        int tipoConta = comboBoxTipoConta.getSelectedIndex();
        
        if(tipoConta == 0){
            Aluno aluno = new Aluno();
            aluno = alunos.buscarAluno(usuario, senha);
            try{
                usuarioSessao = aluno.getUsuario();
                contaSessao = "Aluno";
                nomeSessao = aluno.getNome().split(" ")[0];
                matriculaSessao = aluno.getMatricula();
                TelaHomeAluno telaHomeAluno = new TelaHomeAluno();
                telaHomeAluno.setVisible(true);
                dispose();
            }catch(NullPointerException ex){
                JOptionPane.showMessageDialog(null, "Usuário e/ou senha incorretos", "Erro ao autenticar", JOptionPane.ERROR_MESSAGE); 
                limparCampos();
            }      
        }
        if(tipoConta == 1){
            Bibliotecaria bibliotecaria = new Bibliotecaria();
            bibliotecaria = bibliotecarias.buscarBibliotecaria(usuario, senha);
            try{
                usuarioSessao = bibliotecaria.getUsuario();
                contaSessao = "Biblio";
                nomeSessao = bibliotecaria.getNome().split(" ")[0];
                cpfSessao = bibliotecaria.getCpf();
                TelaHome telaHome = new TelaHome();
                telaHome.setVisible(true);
                dispose();
            }catch(NullPointerException ex){
                JOptionPane.showMessageDialog(null, "Usuário e/ou senha incorretos", "Erro ao autenticar", JOptionPane.ERROR_MESSAGE); 
                limparCampos();
            }      
        }
        
    }
    
    public void loginGuest(String usuario, String senha, int conta){
        
        int tipoConta = conta;
        
        if(tipoConta == 0){
            Aluno aluno = new Aluno();
            aluno = alunos.buscarAluno(usuario, senha);
            try{
                usuarioSessao = aluno.getUsuario();
                contaSessao = "Aluno";
                nomeSessao = aluno.getNome().split(" ")[0];
                matriculaSessao = aluno.getMatricula();
                TelaHomeAluno telaHomeAluno = new TelaHomeAluno();
                telaHomeAluno.setVisible(true);
                dispose();
            }catch(NullPointerException ex){
                JOptionPane.showMessageDialog(null, "Usuário e/ou senha incorretos", "Erro ao autenticar", JOptionPane.ERROR_MESSAGE); 
                limparCampos();
            }      
        }
        if(tipoConta == 1){
            Bibliotecaria bibliotecaria = new Bibliotecaria();
            bibliotecaria = bibliotecarias.buscarBibliotecaria(usuario, senha);
            try{
                usuarioSessao = bibliotecaria.getUsuario();
                contaSessao = "Biblio";
                nomeSessao = bibliotecaria.getNome().split(" ")[0];
                cpfSessao = bibliotecaria.getCpf();
                TelaHome telaHome = new TelaHome();
                telaHome.setVisible(true);
                dispose();
            }catch(NullPointerException ex){
                JOptionPane.showMessageDialog(null, "Usuário e/ou senha incorretos", "Erro ao autenticar", JOptionPane.ERROR_MESSAGE); 
                limparCampos();
            }      
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnSair;
    private javax.swing.JComboBox<String> comboBoxTipoConta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JPasswordField txtSenhaTelaLogin;
    private javax.swing.JTextField txtUsuarioTelaLogin;
    // End of variables declaration//GEN-END:variables
}
