/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.biblioteca.view;

import static br.com.biblioteca.main.Main.livros;
import br.com.biblioteca.model.Livro;
import java.awt.Color;
import java.awt.Frame;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author rf
 */
public class TelaCadastroLivro extends javax.swing.JDialog {

    /**
     * Creates new form TelaCadastroLivro
     */
    String localImagem = null;
    String nomeImagem =  null;
    boolean imagemSelecionada = false;
    private Frame parent;
    
     public TelaCadastroLivro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        txtISBNCadastroLivro.setFont(new java.awt.Font("Ubuntu", 0, 18));
        this.parent = parent;
        this.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTituloCadastroLivro = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtISBNCadastroLivro = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtAutorCadastroLivro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtQuantidadeCadastroLivro = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescricaoCadastroLivro = new javax.swing.JTextArea();
        lblImagem = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        kGradientPanel1.setkEndColor(new java.awt.Color(107, 22, 22));
        kGradientPanel1.setkGradientFocus(250);
        kGradientPanel1.setkStartColor(new java.awt.Color(75, 77, 75));

        jPanel1.setBackground(new java.awt.Color(1, 19, 123));

        jLabel3.setFont(new java.awt.Font("UnPilgi", 1, 48)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Cadastro de Livro");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/biblioteca/images/addlivro.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jLabel3)
                .addGap(44, 44, 44)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGap(16, 16, 16))
        );

        txtTituloCadastroLivro.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        txtTituloCadastroLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloCadastroLivroActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Título:");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("ISBN:");

        txtISBNCadastroLivro.setBackground(new java.awt.Color(255, 255, 255));
        try {
            txtISBNCadastroLivro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-##-###-####-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Quantidade:");

        jLabel9.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setText("Descrição:");

        btnSalvar.setBackground(new java.awt.Color(255, 255, 255));
        btnSalvar.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/biblioteca/images/export.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalvarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalvarMouseEntered(evt);
            }
        });
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelar.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/biblioteca/images/cancel.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarMouseEntered(evt);
            }
        });
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtAutorCadastroLivro.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        txtAutorCadastroLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAutorCadastroLivroActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Autor:");

        txtQuantidadeCadastroLivro.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        txtQuantidadeCadastroLivro.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        txtDescricaoCadastroLivro.setColumns(20);
        txtDescricaoCadastroLivro.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        txtDescricaoCadastroLivro.setRows(5);
        jScrollPane1.setViewportView(txtDescricaoCadastroLivro);

        lblImagem.setBackground(new java.awt.Color(255, 255, 255));
        lblImagem.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblImagem.setForeground(java.awt.Color.white);
        lblImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/biblioteca/images/plus3.png"))); // NOI18N
        lblImagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagemMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setText("Imagem:");

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(6, 6, 6)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                            .addComponent(txtISBNCadastroLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(132, 132, 132)
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                            .addComponent(txtQuantidadeCadastroLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtTituloCadastroLivro)
                        .addComponent(txtAutorCadastroLivro)
                        .addComponent(jScrollPane1)
                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblImagem))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTituloCadastroLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAutorCadastroLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtISBNCadastroLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(txtQuantidadeCadastroLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel10))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTituloCadastroLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloCadastroLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloCadastroLivroActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        String titulo = txtTituloCadastroLivro.getText();
        String autor = txtAutorCadastroLivro.getText();
        String isbn = txtISBNCadastroLivro.getText();
        String descricao = txtDescricaoCadastroLivro.getText();
        String quantidade = String.valueOf(txtQuantidadeCadastroLivro.getValue());
        
        boolean testeCampos = true;

        if(titulo.equals("")){
            testeCampos = false;
            txtTituloCadastroLivro.setBackground(Color.decode("#FF6347"));
        }
        if(autor.equals("")){
            testeCampos = false;
            txtAutorCadastroLivro.setBackground(Color.decode("#FF6347"));
        }
        if(isbn.equals("   -  -   -    - ")){
            testeCampos = false;
            txtISBNCadastroLivro.setBackground(Color.decode("#FF6347"));
        }
        if(descricao.equals("")){
            testeCampos = false;
            txtDescricaoCadastroLivro.setBackground(Color.decode("#FF6347"));
        }
        
        int quantidadeLivro = Integer.parseInt(quantidade);
        
        if(txtQuantidadeCadastroLivro.getValue().equals(0)){
            testeCampos = false;
            txtQuantidadeCadastroLivro.setBackground(Color.decode("#FF6347"));
        }
        if(!testeCampos){
            JOptionPane.showMessageDialog(this, "Preencha todos os campos obrigatórios", "Erro ao realizar o cadastro", JOptionPane.ERROR_MESSAGE);
            pintarCampos();
            return;
        }
        
        if(livros.livroJaCadastrado(isbn)){
            JOptionPane.showMessageDialog(this, "Registro já Encontrado", "Erro ao Realizar Cadastro", JOptionPane.ERROR_MESSAGE);
            limparCampos();
            txtTituloCadastroLivro.requestFocus();
            return;
        }
        
        if(!imagemSelecionada){
            JOptionPane.showMessageDialog(this, "Selecione a Imagem do Livro", "Erro ao Realizar Cadastro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
         String caminho = getClass().getResource("../images/").toString().substring(5);
         Icon livroImage = lblImagem.getIcon();
         System.out.println(caminho);
         File outputfile = new File(caminho+nomeImagem);
         BufferedImage image = null;
         System.out.println(localImagem);
              
        try {
            File arquivo1 = new File(localImagem);
            image = ImageIO.read(arquivo1);
            ImageIO.write(image, "png", outputfile);
        } catch (IOException ex) {
            Logger.getLogger(TelaCadastroLivro.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Livro livro = new Livro();
        livro.setTitulo(titulo);
        livro.setAutor(autor);
        livro.setIsbn(isbn);
        livro.setQuantidade(quantidadeLivro);
        livro.setDescricao(descricao);
        livro.setImagemLivro(livroImage);
        livro.setDisponivel(quantidadeLivro - 1);
        livro.setNomeImagem(nomeImagem);
        livros.adicionarLivro(livro);
        JOptionPane.showMessageDialog(this, "Livro Cadastrado com Sucesso", "Cadastro realizado", JOptionPane.INFORMATION_MESSAGE);
        limparCampos();
    
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        limparCampos();
        dispose();
        this.parent.enable();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtAutorCadastroLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAutorCadastroLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAutorCadastroLivroActionPerformed

    private void lblImagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagemMouseClicked
        // TODO add your handling code here:

        
        String salvaLocal = localImagem;
        String salvaNome = nomeImagem;
        try {
            JFileChooser selecionaImagem = new JFileChooser();
            selecionaImagem.setDialogTitle("Imagem do Livro");
            FileNameExtensionFilter filter = new FileNameExtensionFilter("Imagem","png","jpg","gif","jpeg");
            selecionaImagem.setFileFilter(filter);
            selecionaImagem.showOpenDialog(null);
            localImagem = "" + selecionaImagem.getSelectedFile();
            nomeImagem = "" +selecionaImagem.getSelectedFile().getName();
            ImageIcon imagem = new ImageIcon(localImagem);
            lblImagem.setIcon(new ImageIcon(imagem.getImage().getScaledInstance(162, 162, Image.SCALE_DEFAULT)));
            imagemSelecionada = true;
        } catch (Exception e) {
            localImagem = salvaLocal;
            nomeImagem = salvaNome;
            imagemSelecionada = false;
            JOptionPane.showMessageDialog(null, "Não foi possível carregar o arquivo!");
        }
 
    }//GEN-LAST:event_lblImagemMouseClicked

    private void btnCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseEntered
        // TODO add your handling code here:
        btnCancelar.setBackground(Color.decode("#708090"));
        btnCancelar.setForeground(Color.white);
    }//GEN-LAST:event_btnCancelarMouseEntered

    private void btnCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseExited
        // TODO add your handling code here:
        btnCancelar.setBackground(Color.white);
        btnCancelar.setForeground(Color.black);
    }//GEN-LAST:event_btnCancelarMouseExited

    private void btnSalvarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseEntered
        // TODO add your handling code here:
        btnSalvar.setBackground(Color.decode("#708090"));
        btnSalvar.setForeground(Color.white);
    }//GEN-LAST:event_btnSalvarMouseEntered

    private void btnSalvarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseExited
        // TODO add your handling code here:
        btnSalvar.setBackground(Color.white);
        btnSalvar.setForeground(Color.black);
    }//GEN-LAST:event_btnSalvarMouseExited

    private void limparCampos(){
        txtTituloCadastroLivro.setText("");
        txtAutorCadastroLivro.setText("");
        txtISBNCadastroLivro.setText("");
        txtQuantidadeCadastroLivro.setValue(0);
        txtDescricaoCadastroLivro.setText("");
        lblImagem.setIcon(new ImageIcon(getClass().getResource("/br/com/biblioteca/images/plus3.png")));
        localImagem = null;
        nomeImagem = null;
        imagemSelecionada = false;
    }
    
    private void pintarCampos(){
        txtTituloCadastroLivro.setBackground(Color.white);
        txtAutorCadastroLivro.setBackground(Color.white);
        txtISBNCadastroLivro.setBackground(Color.white);
        txtQuantidadeCadastroLivro.setBackground(Color.white);
        txtDescricaoCadastroLivro.setBackground(Color.white);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaCadastroLivro dialog = new TelaCadastroLivro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JTextField txtAutorCadastroLivro;
    private javax.swing.JTextArea txtDescricaoCadastroLivro;
    private javax.swing.JFormattedTextField txtISBNCadastroLivro;
    private javax.swing.JSpinner txtQuantidadeCadastroLivro;
    private javax.swing.JTextField txtTituloCadastroLivro;
    // End of variables declaration//GEN-END:variables
}
