/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.biblioteca.view;

import static br.com.biblioteca.main.Main.alunos;
import static br.com.biblioteca.main.Main.contaSessao;
import static br.com.biblioteca.main.Main.emprestimos;
import static br.com.biblioteca.main.Main.idEmprestimo;
import static br.com.biblioteca.main.Main.livros;
import br.com.biblioteca.model.Aluno;
import br.com.biblioteca.model.Emprestimo;
import br.com.biblioteca.model.Livro;
import java.awt.Color;
import java.awt.Frame;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author rf
 */
public class TelaSolicitarEmprestimo extends javax.swing.JDialog {

    /**
     * Creates new form TelaSolicitarEmprestimo
     */
    //private Aluno aluno1 = new Aluno();
    private Frame parent;
    
    public TelaSolicitarEmprestimo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        txtMatriculaAlunoEmprestimo.setFont(new java.awt.Font("Ubuntu", 0, 18));
        txtISBNLivroEmprestimo.setFont(new java.awt.Font("Ubuntu", 0, 18));
        inicializaCampos();
        this.parent = parent;
        this.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
     
    }
    
    public TelaSolicitarEmprestimo(java.awt.Frame parent, boolean modal, Aluno aluno) {
        super(parent, modal);
        initComponents();
        this.parent = parent;
        this.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        txtMatriculaAlunoEmprestimo.setFont(new java.awt.Font("Ubuntu", 0, 18));
        txtISBNLivroEmprestimo.setFont(new java.awt.Font("Ubuntu", 0, 18));
        inicializaCampos(aluno);
        
    }
    
    public TelaSolicitarEmprestimo(java.awt.Frame parent, boolean modal, Livro livro) {
        super(parent, modal);
        initComponents();
        this.parent = parent;
        this.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        txtMatriculaAlunoEmprestimo.setFont(new java.awt.Font("Ubuntu", 0, 18));
        txtISBNLivroEmprestimo.setFont(new java.awt.Font("Ubuntu", 0, 18));
        inicializaCampos(livro);
        
    }
    
    public TelaSolicitarEmprestimo(java.awt.Frame parent, boolean modal, Aluno aluno, Livro livro) {
        super(parent, modal);
        initComponents();
        this.parent = parent;
        this.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        txtMatriculaAlunoEmprestimo.setFont(new java.awt.Font("Ubuntu", 0, 18));
        txtISBNLivroEmprestimo.setFont(new java.awt.Font("Ubuntu", 0, 18));
        inicializaCampos(aluno, livro);
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNomeAlunoEmprestimo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMatriculaAlunoEmprestimo = new javax.swing.JFormattedTextField();
        btnSelecionarAluno = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        txtTituloLivroEmprestimo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtISBNLivroEmprestimo = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDisponiveisLivroEmprestimo = new javax.swing.JTextField();
        txtDataEmprestimo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtDataDevolucaoEmprestimo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtIDEmprestimo = new javax.swing.JTextField();
        btnSelecionarLivro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        kGradientPanel1.setkEndColor(new java.awt.Color(107, 22, 22));
        kGradientPanel1.setkGradientFocus(250);
        kGradientPanel1.setkStartColor(new java.awt.Color(75, 77, 75));

        jPanel1.setBackground(new java.awt.Color(1, 19, 123));

        jLabel3.setFont(new java.awt.Font("UnPilgi", 1, 48)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Solicitar Empréstimo");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/biblioteca/images/emprestimoLivro.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGap(16, 16, 16))
        );

        txtNomeAlunoEmprestimo.setEditable(false);
        txtNomeAlunoEmprestimo.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        txtNomeAlunoEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeAlunoEmprestimoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Nome do Aluno:");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Matricula:");

        txtMatriculaAlunoEmprestimo.setBackground(new java.awt.Color(255, 255, 255));
        try {
            txtMatriculaAlunoEmprestimo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtMatriculaAlunoEmprestimo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMatriculaAlunoEmprestimoKeyPressed(evt);
            }
        });

        btnSelecionarAluno.setBackground(new java.awt.Color(255, 255, 255));
        btnSelecionarAluno.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnSelecionarAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/biblioteca/images/cursor.png"))); // NOI18N
        btnSelecionarAluno.setText("Selecionar");
        btnSelecionarAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSelecionarAlunoMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSelecionarAlunoMouseEntered(evt);
            }
        });
        btnSelecionarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarAlunoActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelar.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/biblioteca/images/cancel.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarMouseEntered(evt);
            }
        });
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSalvar.setBackground(new java.awt.Color(255, 255, 255));
        btnSalvar.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/biblioteca/images/export.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalvarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalvarMouseEntered(evt);
            }
        });
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        txtTituloLivroEmprestimo.setEditable(false);
        txtTituloLivroEmprestimo.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        txtTituloLivroEmprestimo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTituloLivroEmprestimoKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Titulo do Livro:");

        txtISBNLivroEmprestimo.setBackground(new java.awt.Color(255, 255, 255));
        try {
            txtISBNLivroEmprestimo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-##-###-####-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtISBNLivroEmprestimo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtISBNLivroEmprestimoKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("ISBN:");

        jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("Disponíveis:");

        txtDisponiveisLivroEmprestimo.setEditable(false);
        txtDisponiveisLivroEmprestimo.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        txtDisponiveisLivroEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDisponiveisLivroEmprestimoActionPerformed(evt);
            }
        });

        txtDataEmprestimo.setEditable(false);
        txtDataEmprestimo.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        txtDataEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataEmprestimoActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("Data de Empréstimo:");

        jLabel9.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setText("Data de Devolução:");

        txtDataDevolucaoEmprestimo.setEditable(false);
        txtDataDevolucaoEmprestimo.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        txtDataDevolucaoEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataDevolucaoEmprestimoActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setText("ID:");

        txtIDEmprestimo.setEditable(false);
        txtIDEmprestimo.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        txtIDEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDEmprestimoActionPerformed(evt);
            }
        });

        btnSelecionarLivro.setBackground(new java.awt.Color(255, 255, 255));
        btnSelecionarLivro.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnSelecionarLivro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/biblioteca/images/cursor.png"))); // NOI18N
        btnSelecionarLivro.setText("Selecionar");
        btnSelecionarLivro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSelecionarLivroMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSelecionarLivroMouseEntered(evt);
            }
        });
        btnSelecionarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarLivroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtTituloLivroEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(28, 28, 28)
                        .addComponent(txtDisponiveisLivroEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(12, 12, 12)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(txtMatriculaAlunoEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSelecionarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtNomeAlunoEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txtISBNLivroEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDataEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDataDevolucaoEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(jLabel10)
                                .addGap(28, 28, 28)
                                .addComponent(txtIDEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(btnSelecionarLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 62, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMatriculaAlunoEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelecionarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNomeAlunoEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtISBNLivroEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSelecionarLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txtDisponiveisLivroEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTituloLivroEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txtIDEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDataEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)))
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDataDevolucaoEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        limparCampos();
        dispose();
        this.parent.enable();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSelecionarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarAlunoActionPerformed
        // TODO add your handling code here:
        txtNomeAlunoEmprestimo.setText("");
        selecionarAluno();
    }//GEN-LAST:event_btnSelecionarAlunoActionPerformed

    private void txtNomeAlunoEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeAlunoEmprestimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeAlunoEmprestimoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        Aluno aluno = new Aluno();
        Livro livro = new Livro();
        String dataEmprestimo = txtDataEmprestimo.getText();
        String dataDevoluvao = txtDataDevolucaoEmprestimo.getText();
        String id = txtIDEmprestimo.getText();
        
        aluno = selecionarAluno();
        if(aluno == null){
            JOptionPane.showMessageDialog(this, "Falha na Solicitação do Livro", "Falha no Empréstimo", JOptionPane.ERROR_MESSAGE);
            return;
        }
        livro = selecionarLivro();
        if(livro == null){
            JOptionPane.showMessageDialog(this, "Falha na Solicitação do Livro", "Falha no Empréstimo", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate dataDoEmprestimo = LocalDate.parse(dataEmprestimo, formato);
        LocalDate dataDaDevolucao = LocalDate.parse(dataDevoluvao, formato);
        int idDoEmprestimo = Integer.parseInt(id);
        
        Emprestimo emprestimo = new Emprestimo(aluno, livro, dataDoEmprestimo, dataDaDevolucao, true, idDoEmprestimo, false);
        
        emprestimos.adicionarEmprestimo(emprestimo);
        aluno.setQuantidadeLivrosAlugados(aluno.getQuantidadeLivrosAlugados() + 1);
        livro.setDisponivel(livro.getQuantidadeDisponivel() - 1);
        
        JOptionPane.showMessageDialog(this, "Empréstimo Realizado com Sucesso", "Empréstimo Realizado", JOptionPane.INFORMATION_MESSAGE);
        idEmprestimo++;
        limparCampos();
        inicializaCampos();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txtDisponiveisLivroEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDisponiveisLivroEmprestimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDisponiveisLivroEmprestimoActionPerformed

    private void txtDataEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataEmprestimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataEmprestimoActionPerformed

    private void txtDataDevolucaoEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataDevolucaoEmprestimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataDevolucaoEmprestimoActionPerformed

    private void txtMatriculaAlunoEmprestimoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMatriculaAlunoEmprestimoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == evt.VK_ENTER){
            txtNomeAlunoEmprestimo.setText("");
            selecionarAluno();
        }
            
    }//GEN-LAST:event_txtMatriculaAlunoEmprestimoKeyPressed

    private void txtIDEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDEmprestimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDEmprestimoActionPerformed

    private void txtTituloLivroEmprestimoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTituloLivroEmprestimoKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtTituloLivroEmprestimoKeyPressed

    private void txtISBNLivroEmprestimoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtISBNLivroEmprestimoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == evt.VK_ENTER){
            txtTituloLivroEmprestimo.setText("");
            selecionarLivro();
        }
    }//GEN-LAST:event_txtISBNLivroEmprestimoKeyPressed

    private void btnSelecionarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarLivroActionPerformed
        // TODO add your handling code here:
        txtTituloLivroEmprestimo.setText("");
        txtDisponiveisLivroEmprestimo.setText("");
        if(contaSessao.equals("Aluno")){
            TelaPesquisaLivroAluno telaPesquisaLivroAluno = new TelaPesquisaLivroAluno(this.parent, false);
            telaPesquisaLivroAluno.setVisible(true);
            telaPesquisaLivroAluno.setLocationRelativeTo(null);
            dispose();
        }else{
            selecionarLivro();
        }
    }//GEN-LAST:event_btnSelecionarLivroActionPerformed

    private void btnSelecionarAlunoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSelecionarAlunoMouseEntered
        // TODO add your handling code here:
        btnSelecionarAluno.setBackground(Color.decode("#708090"));
	btnSelecionarAluno.setForeground(Color.white);
    }//GEN-LAST:event_btnSelecionarAlunoMouseEntered

    private void btnSelecionarAlunoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSelecionarAlunoMouseExited
        // TODO add your handling code here:
        btnSelecionarAluno.setBackground(Color.white);
	btnSelecionarAluno.setForeground(Color.black);
    }//GEN-LAST:event_btnSelecionarAlunoMouseExited

    private void btnSelecionarLivroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSelecionarLivroMouseEntered
        // TODO add your handling code here:
        btnSelecionarLivro.setBackground(Color.decode("#708090"));
	btnSelecionarLivro.setForeground(Color.white);
    }//GEN-LAST:event_btnSelecionarLivroMouseEntered

    private void btnSelecionarLivroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSelecionarLivroMouseExited
        // TODO add your handling code here:
        btnSelecionarLivro.setBackground(Color.white);
	btnSelecionarLivro.setForeground(Color.black);
    }//GEN-LAST:event_btnSelecionarLivroMouseExited

    private void btnCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseEntered
        // TODO add your handling code here:
        btnCancelar.setBackground(Color.decode("#708090"));
	btnCancelar.setForeground(Color.white); 
    }//GEN-LAST:event_btnCancelarMouseEntered

    private void btnCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseExited
        // TODO add your handling code here:
        btnCancelar.setBackground(Color.white);
	btnCancelar.setForeground(Color.black);
    }//GEN-LAST:event_btnCancelarMouseExited

    private void btnSalvarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseEntered
        // TODO add your handling code here:
        btnSalvar.setBackground(Color.decode("#708090"));
	btnSalvar.setForeground(Color.white);
    }//GEN-LAST:event_btnSalvarMouseEntered

    private void btnSalvarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseExited
        // TODO add your handling code here:
        btnSalvar.setBackground(Color.white);
	btnSalvar.setForeground(Color.black);
    }//GEN-LAST:event_btnSalvarMouseExited

    public Aluno selecionarAluno(){
        String matricula = txtMatriculaAlunoEmprestimo.getText();
        if(matricula.contains(" ")){
            txtMatriculaAlunoEmprestimo.setBackground(Color.decode("#FF6347"));
            JOptionPane.showMessageDialog(this, "Preencha o Campo Matricula", "Erro ao Selecionar o Aluno", JOptionPane.ERROR_MESSAGE);
            txtMatriculaAlunoEmprestimo.setBackground(Color.WHITE);
            return null;
        }
        int matricula_aluno = Integer.parseInt(matricula);
        try{
            
            Aluno aluno = new Aluno();
            aluno = alunos.getAlunoMatricula(matricula_aluno);
            if(aluno.getQuantidadeLivrosAlugados() == 4){
                JOptionPane.showMessageDialog(this, "Aluno Com a Quantidade de Livros Máxima", "Falha ao Solicitar Empréstimo", JOptionPane.WARNING_MESSAGE);
                limparCampos();
                return null;
            }
            txtNomeAlunoEmprestimo.setText(aluno.getNome());
            txtISBNLivroEmprestimo.requestFocus();
            return aluno;
        }catch(NullPointerException ex){
            JOptionPane.showMessageDialog(this, "Aluno não Encontrado", "Erro ao Selecionar o Aluno", JOptionPane.ERROR_MESSAGE);
            txtMatriculaAlunoEmprestimo.setText("");
            txtNomeAlunoEmprestimo.setText("");
            txtMatriculaAlunoEmprestimo.requestFocus();
            return null;
        }
        
    }
    
    public Livro selecionarLivro(){
        String isbn = txtISBNLivroEmprestimo.getText();
        if(isbn.contains(" ")){
            txtISBNLivroEmprestimo.setBackground(Color.decode("#FF6347"));
            JOptionPane.showMessageDialog(this, "Preencha o Campo ISBN", "Erro ao Selecionar o Livro", JOptionPane.ERROR_MESSAGE);
            txtISBNLivroEmprestimo.setBackground(Color.WHITE);
            return null;
        }
        try{   
            Livro livro = new Livro();
            livro = livros.getLivroIsbn(isbn);
            if(livro.getQuantidadeDisponivel() == 0){
                JOptionPane.showMessageDialog(this, "Livro Indisponível", "Falha ao Solicitar Empréstimo", JOptionPane.WARNING_MESSAGE);
                limparCampos();
                return null;
            }
            txtTituloLivroEmprestimo.setText(livro.getTitulo());
            txtDisponiveisLivroEmprestimo.setText(String.valueOf(livro.getQuantidadeDisponivel()));
            btnSalvar.requestFocus();
            return livro;
        }catch(NullPointerException ex){
            JOptionPane.showMessageDialog(this, "Livro não Encontrado", "Erro ao Selecionar o Livro", JOptionPane.ERROR_MESSAGE);
            txtISBNLivroEmprestimo.setText("");
            txtTituloLivroEmprestimo.setText("");
            txtDisponiveisLivroEmprestimo.setText("");
            txtISBNLivroEmprestimo.requestFocus();
            return null;
        }
    }
    
    public void limparCampos(){
        txtMatriculaAlunoEmprestimo.setText("");
        txtNomeAlunoEmprestimo.setText("");
        txtTituloLivroEmprestimo.setText("");
        txtISBNLivroEmprestimo.setText("");
        txtDisponiveisLivroEmprestimo.setText("");
        txtDataEmprestimo.setText("");
        txtDataDevolucaoEmprestimo.setText("");
        
    }
    
    public void inicializaCampos(){
        LocalDate dataEmprestimo = LocalDate.now();
        LocalDate dataDevolucao = LocalDate.now().plusDays(15);
        
        String dataDeEmprestimo = String.valueOf(dataEmprestimo);
        String camposDataEmprestimo[] = dataDeEmprestimo.split("-");
        String dataRealizacaoEmprestimo = camposDataEmprestimo[2]+"/"+camposDataEmprestimo[1]+"/"+camposDataEmprestimo[0];
        
        String dataDeDevolucao = String.valueOf(dataDevolucao);
        String camposDataDevolucao[] = dataDeDevolucao.split("-");
        String dataParaDevolucao = camposDataDevolucao[2]+"/"+camposDataDevolucao[1]+"/"+camposDataDevolucao[0];
        
        txtDataEmprestimo.setText(dataRealizacaoEmprestimo);
        txtDataDevolucaoEmprestimo.setText(dataParaDevolucao);
        txtIDEmprestimo.setText(String.valueOf(idEmprestimo));
        
    }
    
    public void inicializaCampos(Aluno aluno){
        inicializaCampos();
        txtMatriculaAlunoEmprestimo.setText(String.valueOf(aluno.getMatricula()));
        txtNomeAlunoEmprestimo.setText(aluno.getNome());
        if(contaSessao.equals("Aluno")){
            txtMatriculaAlunoEmprestimo.setEditable(false);
        }
    }
    
    public void inicializaCampos(Livro livro){
        inicializaCampos();
        txtISBNLivroEmprestimo.setText(livro.getIsbn());
        txtTituloLivroEmprestimo.setText(livro.getTitulo());
        txtDisponiveisLivroEmprestimo.setText(String.valueOf(livro.getQuantidadeDisponivel()));
    }
    
    public void inicializaCampos(Aluno aluno, Livro livro){
        inicializaCampos();
        txtMatriculaAlunoEmprestimo.setEditable(false);
        txtISBNLivroEmprestimo.setEditable(false);
        txtMatriculaAlunoEmprestimo.setText(String.valueOf(aluno.getMatricula()));
        txtNomeAlunoEmprestimo.setText(aluno.getNome());
        txtISBNLivroEmprestimo.setText(livro.getIsbn());
        txtTituloLivroEmprestimo.setText(livro.getTitulo());
        txtDisponiveisLivroEmprestimo.setText(String.valueOf(livro.getQuantidadeDisponivel()));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSolicitarEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSolicitarEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSolicitarEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSolicitarEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaSolicitarEmprestimo dialog = new TelaSolicitarEmprestimo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnSelecionarAluno;
    private javax.swing.JButton btnSelecionarLivro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JTextField txtDataDevolucaoEmprestimo;
    private javax.swing.JTextField txtDataEmprestimo;
    private javax.swing.JTextField txtDisponiveisLivroEmprestimo;
    private javax.swing.JTextField txtIDEmprestimo;
    private javax.swing.JFormattedTextField txtISBNLivroEmprestimo;
    private javax.swing.JFormattedTextField txtMatriculaAlunoEmprestimo;
    private javax.swing.JTextField txtNomeAlunoEmprestimo;
    private javax.swing.JTextField txtTituloLivroEmprestimo;
    // End of variables declaration//GEN-END:variables
}
