/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.biblioteca.view;

import br.com.biblioteca.main.Main;
import static br.com.biblioteca.main.Main.bibliotecarias;
import static br.com.biblioteca.main.Main.nomeSessao;
import static br.com.biblioteca.main.Main.usuarioSessao;
import br.com.biblioteca.model.Bibliotecaria;
import java.awt.Color;
import java.awt.Frame;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author rf
 */
public class TelaInfoEditBibliotecaria extends javax.swing.JDialog {

    /**
     * Creates new form TelaInfoEditBibliotecaria
     */
    private Bibliotecaria bibliotecaria;
    private Frame parent;
    private JLabel lblNome;
    private JLabel lblUsuario;
    private boolean isPerfil;
    
    public TelaInfoEditBibliotecaria(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
    }
    
    public TelaInfoEditBibliotecaria(java.awt.Frame parent, boolean modal, Bibliotecaria bibliotecaria, boolean edit, boolean isPerfil) {
        super(parent, modal);
        initComponents();
        this.parent = parent;
        this.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        txtCPFInfoBibliot.setFont(new java.awt.Font("Ubuntu", 0, 18));
        txtTelefoneInfoBibliot.setFont(new java.awt.Font("Ubuntu", 0, 18));
        txtRGInfoBibliot.setFont(new java.awt.Font("Ubuntu", 0, 18));
        txtDataNascInfoBibliot.setFont(new java.awt.Font("Ubuntu", 0, 18));
        inicializaCampos(bibliotecaria);
        this.bibliotecaria = bibliotecaria;
        if(!edit){
            bloqueiaCampos();
        }
        this.isPerfil = isPerfil;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNomeInfoBibliot = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCPFInfoBibliot = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTelefoneInfoBibliot = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDataNascInfoBibliot = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        txtUsuarioInfoBibliot = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtSenhaInfoBibliot = new javax.swing.JPasswordField();
        btnSalvar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtRGInfoBibliot = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        kGradientPanel1.setkEndColor(new java.awt.Color(107, 22, 22));
        kGradientPanel1.setkGradientFocus(250);
        kGradientPanel1.setkStartColor(new java.awt.Color(75, 77, 75));

        jPanel1.setBackground(new java.awt.Color(1, 19, 123));

        jLabel3.setFont(new java.awt.Font("UnPilgi", 1, 48)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Informações de Bibliotecária");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/biblioteca/images/userbibl.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGap(16, 16, 16))
        );

        txtNomeInfoBibliot.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        txtNomeInfoBibliot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeInfoBibliotActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Nome:");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("CPF:");

        txtCPFInfoBibliot.setBackground(new java.awt.Color(255, 255, 255));
        try {
            txtCPFInfoBibliot.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Telefone:");

        try {
            txtTelefoneInfoBibliot.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel8.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("Data de Nascimento:");

        txtDataNascInfoBibliot.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        jLabel9.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setText("Usuário:");

        txtUsuarioInfoBibliot.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        txtUsuarioInfoBibliot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioInfoBibliotActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setText("Senha:");

        txtSenhaInfoBibliot.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        btnSalvar.setBackground(new java.awt.Color(255, 255, 255));
        btnSalvar.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/biblioteca/images/export.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalvarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalvarMouseEntered(evt);
            }
        });
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnVoltar.setBackground(new java.awt.Color(255, 255, 255));
        btnVoltar.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/biblioteca/images/cancel.png"))); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVoltarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVoltarMouseEntered(evt);
            }
        });
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel11.setForeground(java.awt.Color.white);
        jLabel11.setText("RG:");

        txtRGInfoBibliot.setBackground(new java.awt.Color(255, 255, 255));
        try {
            txtRGInfoBibliot.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##########-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(40, 40, 40)))
                            .addComponent(jLabel11))
                        .addGap(12, 12, 12)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(txtCPFInfoBibliot, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtNomeInfoBibliot)))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(24, 24, 24)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addComponent(txtRGInfoBibliot, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel8))
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel6)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDataNascInfoBibliot)
                                    .addComponent(txtTelefoneInfoBibliot, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)))
                            .addComponent(txtSenhaInfoBibliot)
                            .addComponent(txtUsuarioInfoBibliot))))
                .addGap(39, 39, 39))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNomeInfoBibliot, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCPFInfoBibliot, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtTelefoneInfoBibliot, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtDataNascInfoBibliot, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtRGInfoBibliot, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuarioInfoBibliot, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(13, 13, 13)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtSenhaInfoBibliot, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeInfoBibliotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeInfoBibliotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeInfoBibliotActionPerformed

    private void txtUsuarioInfoBibliotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioInfoBibliotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioInfoBibliotActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        String nome = txtNomeInfoBibliot.getText();
        String cpf = txtCPFInfoBibliot.getText();
        String telefone = txtTelefoneInfoBibliot.getText();
        String rg = txtRGInfoBibliot.getText();
        String dataNasc = txtDataNascInfoBibliot.getText();
        String usuario = txtUsuarioInfoBibliot.getText();
        String senha = txtSenhaInfoBibliot.getText();
        boolean testeCampos = true;
        boolean alterarLabel = false;

        if(nome.equals("")){
            testeCampos = false;
            txtNomeInfoBibliot.setBackground(Color.decode("#FF6347"));
        }
        if(cpf.equals("   .   .   -  ")){
            testeCampos = false;
            txtCPFInfoBibliot.setBackground(Color.decode("#FF6347"));
        }
        if(telefone.equals("(  )      -    ")){
            testeCampos = false;
            txtTelefoneInfoBibliot.setBackground(Color.decode("#FF6347"));

        }
        if(rg.equals("          - ")){
            testeCampos = false;
            txtRGInfoBibliot.setBackground(Color.decode("#FF6347"));
        }
        if(dataNasc.equals("")){
            testeCampos = false;
            txtDataNascInfoBibliot.setBackground(Color.decode("#FF6347"));
        }
        if(usuario.equals("")){
            testeCampos = false;
            txtUsuarioInfoBibliot.setBackground(Color.decode("#FF6347"));
        }
        if(senha.equals("")){
            testeCampos = false;
            txtSenhaInfoBibliot.setBackground(Color.decode("#FF6347"));
        }

        if(!testeCampos){
            JOptionPane.showMessageDialog(this, "Preencha todos os campos obrigatórios", "Erro ao realizar o cadastro", JOptionPane.ERROR_MESSAGE);
            txtNomeInfoBibliot.requestFocus();
            pintarCampos();
            return;
        }

        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate dataNascimento = LocalDate.parse(dataNasc, formato);

        if(bibliotecarias.bibliotecariaJaCadastrada(usuario, cpf, this.bibliotecaria)){
            JOptionPane.showMessageDialog(this, "Registro já Encontrado", "Erro ao Atualizar Cadastro", JOptionPane.ERROR_MESSAGE);
            limparCampos();
            txtNomeInfoBibliot.requestFocus();
            inicializaCampos(bibliotecaria);
            return;
        }
        
        if(bibliotecaria.getUsuario().equals(usuarioSessao)){
            alterarLabel = true;
            
        }

        bibliotecaria.setNome(nome);
        bibliotecaria.setCpf(cpf);
        bibliotecaria.setRg(rg);
        bibliotecaria.setDataNascimento(dataNascimento);
        bibliotecaria.setUsuario(usuario);
        bibliotecaria.setSenha(senha);
        
        JOptionPane.showMessageDialog(this, "Bibliotecaria Atualizada com Sucesso", "Alteração realizada", JOptionPane.INFORMATION_MESSAGE);
        
        
        
        limparCampos();
        if(!isPerfil){
            TelaPesquisaBibliotecaria pesquisaBibliotecaria = new TelaPesquisaBibliotecaria(this.parent, false);
            pesquisaBibliotecaria.setVisible(true);
            pesquisaBibliotecaria.setLocationRelativeTo(null);
        }
        dispose();
        this.parent.enable();
        if(alterarLabel){
            TelaLogin login = new TelaLogin();
            login.loginGuest(bibliotecaria.getUsuario(), bibliotecaria.getSenha(), 1);
            this.parent.dispose();
        }    
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        limparCampos();
        if(!this.isPerfil){
            TelaPesquisaBibliotecaria pesquisaBibliotecaria = new TelaPesquisaBibliotecaria(this.parent, false);
            pesquisaBibliotecaria.setVisible(true);
            pesquisaBibliotecaria.setLocationRelativeTo(null);
        }
        dispose();
        this.parent.enable();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnVoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarMouseEntered
        // TODO add your handling code here:
        btnVoltar.setBackground(Color.decode("#708090"));
        btnVoltar.setForeground(Color.white);
    }//GEN-LAST:event_btnVoltarMouseEntered

    private void btnVoltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarMouseExited
        // TODO add your handling code here:
        btnVoltar.setBackground(Color.white);
        btnVoltar.setForeground(Color.black);
    }//GEN-LAST:event_btnVoltarMouseExited

    private void btnSalvarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseEntered
        // TODO add your handling code here:
        btnSalvar.setBackground(Color.decode("#708090"));
        btnSalvar.setForeground(Color.white);
    }//GEN-LAST:event_btnSalvarMouseEntered

    private void btnSalvarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseExited
        // TODO add your handling code here:
        btnSalvar.setBackground(Color.white);
        btnSalvar.setForeground(Color.black);
    }//GEN-LAST:event_btnSalvarMouseExited
    
    public void limparCampos(){
        txtNomeInfoBibliot.setText("");
        txtCPFInfoBibliot.setText("");
        txtTelefoneInfoBibliot.setText("");
        txtRGInfoBibliot.setText("");
        txtDataNascInfoBibliot.setText("");
        txtUsuarioInfoBibliot.setText("");
        txtSenhaInfoBibliot.setText("");
    }
    
    public void pintarCampos(){
        txtNomeInfoBibliot.setBackground(Color.WHITE);
        txtCPFInfoBibliot.setBackground(Color.WHITE);
        txtTelefoneInfoBibliot.setBackground(Color.WHITE);
        txtRGInfoBibliot.setBackground(Color.WHITE);
        txtDataNascInfoBibliot.setBackground(Color.WHITE);
        txtUsuarioInfoBibliot.setBackground(Color.WHITE);
        txtSenhaInfoBibliot.setBackground(Color.WHITE);
    }
    
    public void inicializaCampos(Bibliotecaria bibliotecaria){
        txtNomeInfoBibliot.setText(bibliotecaria.getNome());
        txtCPFInfoBibliot.setText(bibliotecaria.getCpf());
        txtTelefoneInfoBibliot.setText(bibliotecaria.getTelefone());
        txtRGInfoBibliot.setText(bibliotecaria.getRg());
        txtUsuarioInfoBibliot.setText(bibliotecaria.getUsuario());
        txtSenhaInfoBibliot.setText(bibliotecaria.getSenha());
        
        String data = String.valueOf(bibliotecaria.getDataNascimento());
        String camposData[] = data.split("-");
        String dataNascimento = camposData[2]+"/"+camposData[1]+"/"+camposData[0];
        txtDataNascInfoBibliot.setText(dataNascimento);
    }
    
    public void bloqueiaCampos(){
        txtNomeInfoBibliot.setEditable(false);
        txtCPFInfoBibliot.setEditable(false);
        txtTelefoneInfoBibliot.setEditable(false);
        txtRGInfoBibliot.setEditable(false);
        txtDataNascInfoBibliot.setEditable(false);
        txtUsuarioInfoBibliot.setEditable(false);
        txtSenhaInfoBibliot.setEditable(false);
        btnSalvar.setEnabled(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInfoEditBibliotecaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInfoEditBibliotecaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInfoEditBibliotecaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInfoEditBibliotecaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaInfoEditBibliotecaria dialog = new TelaInfoEditBibliotecaria(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JFormattedTextField txtCPFInfoBibliot;
    private javax.swing.JFormattedTextField txtDataNascInfoBibliot;
    private javax.swing.JTextField txtNomeInfoBibliot;
    private javax.swing.JFormattedTextField txtRGInfoBibliot;
    private javax.swing.JPasswordField txtSenhaInfoBibliot;
    private javax.swing.JFormattedTextField txtTelefoneInfoBibliot;
    private javax.swing.JTextField txtUsuarioInfoBibliot;
    // End of variables declaration//GEN-END:variables
}
